### ISSUE TITLE
百度贴吧接口合集 链接失效

### ISSUE THREAD

**Issue by zhtjtcz** [Starry-OvO/Tieba-Cloud-Review#10]
README 文件中的友情链接中的第一个超链接`百度贴吧接口合集`，链接到的地址为`https://github.com/Starry-OvO/Tieba-Manager/blob/master/aiotieba/_api.py`，是一个无效地址。

**Comment by dog194** [comment]
https://github.com/Starry-OvO/Tieba-Manager/blob/master/aiotieba/client.py

**Comment by lumina37** [comment]
已修复，感谢建议
现在的正确链接为[https://github.com/Starry-OvO/Tieba-Manager/blob/master/aiotieba/client.py](https://github.com/Starry-OvO/Tieba-Manager/blob/master/aiotieba/client.py)
