### ISSUE TITLE
protobuf接口的websocket

### ISSUE THREAD

**Issue by n0099** [Starry-OvO/Tieba-Cloud-Review#105]
https://github.com/Starry-OvO/aiotieba/releases/tag/v3.2.0
> 所有使用prorobuf序列化请求参数的接口现在都支持 websocket 模式，使用 Client(enable_ws=True) 以启用并优先使用 websocket 。 websocket 模式的优势是： get_threads 和 get_posts 的响应会使用 gzip 压缩；预期稳定性更好

https://github.com/Starry-OvO/aiotieba/commit/99c48b1a94dd31d01aeeb9fa59d47ba24cdaa9a0
[`46d7bd2` (#104)](https://github.com/Starry-OvO/aiotieba/pull/104/commits/46d7bd299f20a3d5da34bfc8ff08d46a0bebc2af#diff-ee293414c387c0b871c8c22d4607f4b15b3e0f5234fd3a14ed0c31dfd81ff175R66)
1. 所以请求接口是什么？ https://github.com/Starry-OvO/aiotieba/blob/baa0d781028edd4705d51f6013d1e6966011cc5d/aiotieba/client/_core/_wscore.py#L180 `im.tieba.baidu.com:8000`不是阁下去年挖出来的私信接口吗？ https://www.52pojie.cn/thread-1648818-1-1.html
2. > get_threads 和 get_posts 的响应会使用 gzip 压缩

   3大接口不本来就有response header之`Content-Encoding: gzip`吗？阁下是否忘了在request header中加`Accept-Encoding: gzip`？（但他们一直不支持`HTTP/2`和`brotli`，而且对于本就是二进制结构的protobuf encoding压缩也就压缩掉重复字符串）
4. > 预期稳定性更好

   什么稳定性？难道给protobuf接口套一层ws都去ws endpoint url而不是每接口url那请求所返回的protobuf结构不同吗？（如同不同`_client_version`带来的效果 https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368182846 ）
6. 另外由于`c.tieba.baidu.com`下的endpoint不支持`HTTP/2`，所以阁下此前于 3886edf3e7c2dd4fa18ef24a35fab2802a1761bd 和 7b7bba9da8491584af848d53eaa8bc4ec7a71bd3 把改成一堆接口的url scheme改成https反而会更慢（当然贴吧方面要求携带BDUSS cookie的接口必须https是合理的），我以前curl测试http要300ms左右而https要600ms左右，而如果他们哪天支持了`HTTP/2`那复用现有的connection就可以压缩response header中那一堆重复的cookie（不论您的request header多简洁有无BDUSS他们都会返回一堆遥测tracing用途的cookie）

**Comment by lumina37** [comment]
1、自行阅读理解cmd的作用
2、自行抓包
3、绝大部分用户都走ws
