### ISSUE TITLE
希望添加楼中楼回复的功能

### ISSUE THREAD

**Issue by Allan0423** [Starry-OvO/Tieba-Cloud-Review#109]
**我需要什么功能**

需要在某个指定的楼层中进行回复的功能。

**我想将这个功能应用于何种场景**

在一个贴子的某个楼层中添加回复，同时有可能是回复给已经存在的楼中楼的某个用户。

**Comment by lumina37** [comment]
发帖接口可用性很差，白板号扛不过十五条就永封了，加个楼中楼功能也没什么意义

**Comment by Allan0423** [comment]
> 发帖接口可用性很差，白板号扛不过十五条就永封了，加个楼中楼功能也没什么意义

原来如此，谢谢解答。
