### ISSUE TITLE
无法获取楼中楼

### ISSUE THREAD

**Issue by qimuwen** [Starry-OvO/Tieba-Cloud-Review#113]
**无法获取到楼中楼**
1.client.get_posts(tid=8354539603,only_thread_author=False,with_comments=True,comment_sort_by_agree=True,rn=30)
通过get_posts没有获取到楼中楼信息
返回列表key：['floor','text','tid','user','vimage‘]
2.client.get_comments(pn=1,tid=8354539603,pid=147346323674,is_floor=True)
通过get_comments获取到的信息为
<2023-04-20 10:10:38.962> [WARN] [get_comments] (4, '贴子可能已被删除'). 
确认tid和pid无误

**Comment by n0099** [comment]
https://tieba.baidu.com/p/8354539603?pid=147346323674#147346323674
![image](https://user-images.githubusercontent.com/13030387/233267051-b70e34bf-4075-449e-adec-40aa01d388e1.png)
`pid147346323674`是`tid8354539603`的1L，请问1L哪来的楼中楼？（虽然理论上当然可以存在，如果在历史上某个时期有某位贴吧后端程序员在某个发楼中楼接口中忘了检查回复的pid是否为其父tid1L，但我从来没见过）

**Comment by mrzhu666** [comment]
> **无法获取到楼中楼** 1.client.get_posts(tid=8354539603,only_thread_author=False,with_comments=True,comment_sort_by_agree=True,rn=30) 通过get_posts没有获取到楼中楼信息 返回列表key：['floor','text','tid','user','vimage‘] 2.client.get_comments(pn=1,tid=8354539603,pid=147346323674,is_floor=True) 通过get_comments获取到的信息为 <2023-04-20 10:10:38.962> [WARN] [get_comments] (4, '贴子可能已被删除'). 确认tid和pid无误

我刚看过源码，他有些地方写错了，而且文档那里也没更新。
key那里只是因为没有全部属性打印出来，你要去看源码定义的类有什么属性。

**Comment by n0099** [comment]
> 你要去看源码定义的类有什么属性

#114

**Comment by qimuwen** [comment]
> > 你要去看源码定义的类有什么属性
> 
> #114

谢谢已经找到了

**Comment by qimuwen** [comment]
> > **无法获取到楼中楼**1.client.get_posts（tid=8354539603，only_thread_author=False，with_comments=True，comment_sort_by_agree=True，rn=30） 通过get_posts没有获取到楼中楼信息 返回列表key：['floor'，'text'，'tid'，'user'，'vimage'] 2.client.get_comments（pn=1，tid=8354539603，pid=147346323674，is_floor=True） 通过get_comments获取到的信息为 <2023-04-20 10：10：38.962> [WARN] [get_comments] （4， '贴子可能已被删除'）.确认tid和pid无误
> 
> 我刚看过源码，他有些地方写错了，而且文档那里也没更新。 key那里只是因为没有全部属性打印出来，你要去看源码定义的类有什么属性。

嗯嗯，找到了，谢谢

**Comment by lumina37** [comment]
> 我刚看过源码，他有些地方写错了，而且文档那里也没更新。 key那里只是因为没有全部属性打印出来，你要去看源码定义的类有什么属性。

文档是哪个地方出了问题

好吧我刚刚也发现有点问题，小修了一下`pid`相关的文档 04e8fc571b8cabb047433bea8b76354305837c72
