### ISSUE TITLE
get_posts方法的_classdef.py的Comment_p类的ppid属性返回错了

### ISSUE THREAD

**Issue by mrzhu666** [Starry-OvO/Tieba-Cloud-Review#114]
![Snipaste_2023-04-20_14-01-17](https://user-images.githubusercontent.com/47910447/233271871-ca2886a2-1325-4126-ad37-1991d57cb7f4.png)

而且为什么每一个方法都要定义自己的返回类？并且都是重复的

**Comment by n0099** [comment]
楼中楼id不应该叫spid（贴吧内部命名）？
ppid疑似unix风格缩写之`parent-`，然而这样还不如直接把回复贴id叫pid，楼中楼id叫spid（尽管pid spid本质都共享同一个id空间因为回复贴和楼中楼本质完完全全一路人），正如同 https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1368602636
> https://github.com/Starry-OvO/aiotieba/commit/ef8a8c382449833716650c16aca118f98c9492eb#r94765151 进一步指出：
> 
> > p本就是post的缩写
> > 贴吧泰国第几的en水平指导下的内部命名是
> > 
> > * 吧forum
> > * 主题帖thread
> > * 回复贴post
> > * 楼中楼subpost（考虑到13年10月才引入楼中楼叫subpost也不奇怪）
> > 
> > 让我想起了flarum把主题帖叫discussion，phpbb的主题帖叫topic，而两者的回复贴都叫post
> > 而tbm的命名是：
> > 
> > * 吧forum
> > * 对以下3种帖子的统称post（可以用来命名抽象类）
> > * 主题帖thread
> > * 回复贴reply
> > * 楼中楼subreply

https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1397550279
> 居然不是indoor post或者post in post

> 每一个方法都要定义自己的返回类

可能是为了链式调用

**Comment by mrzhu666** [comment]
> 楼中楼id不应该叫spid（贴吧内部命名）？ ppid疑似unix风格缩写之`parent-`，然而这样还不如直接把回复贴id叫pid，楼中楼id叫spid（尽管pid spid本质都共享同一个id空间因为回复贴和楼中楼本质完完全全一路人），正如同 [#63 (comment)](https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1368602636)
> 
> > [ef8a8c3#r94765151](https://github.com/Starry-OvO/aiotieba/commit/ef8a8c382449833716650c16aca118f98c9492eb#r94765151) 进一步指出：
> > > p本就是post的缩写
> > > 贴吧泰国第几的en水平指导下的内部命名是
> > > 
> > > * 吧forum
> > > * 主题帖thread
> > > * 回复贴post
> > > * 楼中楼subpost（考虑到13年10月才引入楼中楼叫subpost也不奇怪）
> > > 
> > > 让我想起了flarum把主题帖叫discussion，phpbb的主题帖叫topic，而两者的回复贴都叫post
> > > 而tbm的命名是：
> > > 
> > > * 吧forum
> > > * 对以下3种帖子的统称post（可以用来命名抽象类）
> > > * 主题帖thread
> > > * 回复贴reply
> > > * 楼中楼subreply
> 
> [#63 (comment)](https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1397550279)
> 
> > 居然不是indoor post或者post in post
> 
> > 每一个方法都要定义自己的返回类
> 
> 可能是为了链式调用

这里的ppid等于贴吧的pid，pid等于贴吧的spid。
Comment_p类应该是写错的，get_comments方法的Comment类返回的ppid是正确的。

**Comment by lumina37** [comment]
这个`Comment_p.ppid`确实是一个复制粘贴导致的bug。定义property是为了让pylance显示注释。至于各种命名，那确实是习惯问题，而我这里主要是因为删帖接口所用的`pid`并不区分楼中楼和楼层，所以我把更不常用的“所在回复id”命名成了`ppid`

**Comment by n0099** [comment]
> 删帖接口所用的pid并不区分楼中楼和楼层

上面说了

> 尽管pid spid本质都共享同一个id空间因为回复贴和楼中楼本质完完全全一路人

也就是由于13年10月才引入楼中楼所以在贴吧架构师看来楼中楼不过就是特殊的回复贴
