### ISSUE TITLE
你好，调用client.get_self_info()和client.add_post()时会出现「用户未登录或登录失败，请更换账号或重试」和「用户名或密码错误」的错误

### ISSUE THREAD

**Issue by ovixiao** [Starry-OvO/Tieba-Cloud-Review#116]
你好，aiotieba非常好用！非常感谢你们。

我在使用过程中获取threads等操作都非常顺滑和高效，但是在需要个人信息的时候（例如：`client.get_self_info()`和`client.add_post()`）会出现「用户未登录或登录失败，请更换账号或重试」和「用户名或密码错误」的错误。

我已经配置好了BDUSS，是否还有其他字段可以配置用户名和密码？我在官网和文档中都没有找到（也可能我查阅不够细致），请告知这种情况要怎么处理。

**再次感谢！**

附上代码片段：
```
import asyncio
import aiotieba

async def main():
    async with aiotieba.Client() as client:
        info = await client.get_self_info()
        print(info)

        ok = await client.add_post(24091, 8395194224, "试一下试一下")
        print(ok)

asyncio.run(main())
```

错误信息如下：
```
<2023-05-05 18:16:56.432> [WARN] [__login] (2, '用户名或密码错误'). 
<2023-05-05 18:16:56.476> [WARN] [__get_selfinfo_initNickname] (1, '用户未登录或登录失败，请更换账号或重试'). 
<2023-05-05 18:16:56.779> [WARN] [__login] (2, '用户名或密码错误'). 
<2023-05-05 18:16:57.411> [WARN] [add_post] (1, '用户未登录或登录失败，请更换账号或重试'). fname=水 tid=8395194224
```

我的配置信息（aiotieba.toml）如下，配置了BDUSS和STOKEN：
```
[User]
[User.default]
BDUSS = "NyLUZXMlhRaG93NXVzbHZyV0ZSMkc5QnJ1TWpTa2……"
STOKEN = "e2bb9908bd606d62f2cbcbe6cb9d406d05d……"
```

**Comment by lumina37** [comment]
要把`aiotieba.Client()`改成`aiotieba.Client("default")`，那个`"default"`就是用来决定将要使用哪个账号的`BDUSS_key`
另外这个`add_post`方法，我还没有完美还原请求参数，新号发个十几条就会被封，非常非常危险，不建议用大号尝试

**Comment by n0099** [comment]
> `ok = await client.add_post(24091, 8395194224, "试一下试一下")`

https://tieba.baidu.com/p/8395194224
玩原神玩的

**Comment by ovixiao** [comment]
非常感谢，已经成功发送！
