### ISSUE TITLE
你好。使用 `client.send_msg()` 时会报超时的错误。

### ISSUE THREAD

**Issue by ovixiao** [Starry-OvO/Tieba-Cloud-Review#119]
你好，aiotieba。
在使用过程中调用`client.send_msg()`会报超时的错误，我看到问题是出在`client.__init_websocket()`，不知道要怎么能正常使用。

**再一次非常感谢！***

附上代码：
```
import asyncio
import aiotieba

uid = 3357704***

async def main():
    async with aiotieba.Client("default") as client:
        ok = await client.send_msg(uid, "你好")
        print(ok)

asyncio.run(main())
```

错误信息为：
```
<2023-05-08 15:37:07.476> [WARN] [send_msg] Timeout to read. user_id=3357704***
```

**Comment by lumina37** [comment]
我这里没问题啊

```log
<2023-05-08 21:43:36.731> [INFO] [send_msg] Suceeded. user_id=957339815
True
```

试一下`ping im.tieba.baidu.com`看看能不能ping通
另外windows10/11+python3.11好像有时候连websocket连得特别慢，但ubuntu20/22都很顺畅，我感觉实现是没问题的

**Comment by ovixiao** [comment]
非常感谢你的回答。

我发现在我的笔记本上会运行错误，但是服务器上就可以正常运行。我做了如下测试：

1. 笔记本直连能ping通，但是建立ws链接会出错
2. 笔记本挂全局VPN（外网），能ping通，但是建立ws连接会出错（和没挂VPN一样）
3. 在腾讯云服务器上正常使用！

可能和机器有关，我的笔记本是Macbook Air M1 2020款，不确定是不是这个原因。

**总之，非常感谢！**

*P.S. 不知道`send_msg`的发送频次多少会可能被封？不知你是否有做过相关调研。*

**Comment by n0099** [comment]
#116
您就是贴吧私信bot广告机贩子？
https://github.com/Starry-OvO/aiotieba-reviewer/issues/15#issuecomment-1516782078 对此早有预言
> 试想一个更严重的情况，对v88u进行长期迫害的群体，想要获取`上海贵族贴吧辅助工具皇帝鸡血神` @bakasnow 密友山东土著 @Juicpt 神所开发的的`贴吧辅助工具`，并且竭泽而渔试图逼死你。starry神的工具越好用，则这个过程会更极端。要面对的不是有合法性的吧务使用者，而是没有道德观的网络皇帝。

**Comment by n0099** [comment]
> 试一下ping im.tieba.baidu.com看看能不能ping通

https://github.com/Starry-OvO/aiotieba/blob/ebce2656c1329ca2a5b58bcb162f48a8687f87b1/aiotieba/core/websocket.py#L246
建议直接`tcpping im.tieba.baidu.com 8000`
建议 https://curl.se/docs/websocket.html

**Comment by lumina37** [comment]
没测试过频率，不过既然是极速版私信自然性能不会太好，有时候甚至会吞私信

**Comment by ovixiao** [comment]
> #116 您就是贴吧私信bot广告机贩子？ [Starry-OvO/aiotieba-reviewer#15 (comment)](https://github.com/Starry-OvO/aiotieba-reviewer/issues/15#issuecomment-1516782078) 对此早有预言
> 
> > 试想一个更严重的情况，对v88u进行长期迫害的群体，想要获取`上海贵族贴吧辅助工具皇帝鸡血神` @bakasnow 密友山东土著 @Juicpt 神所开发的的`贴吧辅助工具`，并且竭泽而渔试图逼死你。starry神的工具越好用，则这个过程会更极端。要面对的不是有合法性的吧务使用者，而是没有道德观的网络皇帝。

你好，我并不是广告贩子，我只是想每个接口都试一遍。

**Comment by ovixiao** [comment]
> 没测试过频率，不过既然是极速版私信自然性能不会太好，有时候甚至会吞私信

好的，感激不尽！

**Comment by ovixiao** [comment]
> > 试一下ping im.tieba.baidu.com看看能不能ping通
> 
> https://github.com/Starry-OvO/aiotieba/blob/ebce2656c1329ca2a5b58bcb162f48a8687f87b1/aiotieba/core/websocket.py#L246
> 
> 
> 建议直接`tcpping im.tieba.baidu.com 8000`
> 建议 https://curl.se/docs/websocket.html

是可以ping通的：

```
➜  ~ tcping im.tieba.baidu.com 8000
14.215.177.132 port 8000 open.
```

**Comment by n0099** [comment]
用curl replay一遍aiotieba发的ws包，建议同时开着tcpdump视奸

**Comment by lumina37** [comment]
贴吧后端最近又在暴动，今天中午有一段时间极速版发帖秒删，私信和发回复都是用的9.1.0.0的极速版版本号，这两个接口最近可能会格外危险

**Comment by n0099** [comment]
那他们有乱改接口返回结构吗？如同年初的 https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368179653

**Comment by lumina37** [comment]
不确定有没有，但估计都是后端在改内部策略，外部接口不变
