### ISSUE TITLE
setup.py构建得到的so文件在导入时显示undefined symbol: u64toa

### ISSUE THREAD

**Issue by Hawaii-ol** [Starry-OvO/Tieba-Cloud-Review#126]
起因是我遇到了跟Starry-OvO/aiotieba-reviewer#14 一样的问题，通过`pip install`安装的aiotieba在运行时会报`Segmentation fault`
通过gdb调试了一下发现是`tbc_heliosHash`调用libz时挂了，可能是libz的版本有问题？
<img width="774" alt="屏幕截图 2023-06-05 034503" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/83d39278-d16f-4b79-afb1-4472303e669a">
总之我转而尝试`clone`源码编译，`python3 setup.py build`成功生成了so文件，把它拷贝到`aiotieba/helper/crypto`下，重新运行`python3 my_reviewer.py`，结果出现以下报错
```
root@vultr:~/aiotieba-reviewer# python3 my_reviewer.py 
Traceback (most recent call last):
  File "/root/aiotieba-reviewer/my_reviewer.py", line 8, in <module>
    import aiotieba as tb
  File "/root/aiotieba-reviewer/aiotieba/__init__.py", line 11, in <module>
    from . import const, core, enums, exception, typing
  File "/root/aiotieba-reviewer/aiotieba/core/__init__.py", line 1, in <module>
    from .account import Account
  File "/root/aiotieba-reviewer/aiotieba/core/account.py", line 8, in <module>
    from ..helper.crypto import c3_aid, cuid_galaxy2
  File "/root/aiotieba-reviewer/aiotieba/helper/__init__.py", line 2, in <module>
    from . import cache, crypto, utils
  File "/root/aiotieba-reviewer/aiotieba/helper/crypto/__init__.py", line 3, in <module>
    from .crypto import c3_aid, cuid_galaxy2, rc4_42
ImportError: /root/aiotieba-reviewer/aiotieba/helper/crypto/crypto.cpython-310-x86_64-linux-gnu.so: undefined symbol: u64toa
```
于是我又去找哪里出现了u64toa，发现是
```
root@vultr:~/aiotieba-reviewer/aiotieba-src# grep -rnw . -e 'u64toa'
./thirdparty/rapidjson/internal/itoa.h:35:inline char *u64toa(uint64_t value, char *buffer)
./thirdparty/rapidjson/internal/itoa.h:222:    return u64toa(u, buffer);
grep: ./build/temp.linux-x86_64-3.10/aiotieba/helper/crypto/sign.o: binary file matches
grep: ./build/lib.linux-x86_64-3.10/aiotieba/helper/crypto/crypto.cpython-310-x86_64-linux-gnu.so: binary file matches
grep: ./aiotieba/helper/crypto/crypto.cpython-310-x86_64-linux-gnu.so: binary file matches
```
所以应该是`sign.c`这个文件include了`itoa.h`中定义的`inline char *u64toa`，我nm看了一下`sign.o`中确实缺少`u64toa`的符号定义
<img width="614" alt="屏幕截图 2023-06-05 042213" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/33e11d4d-9593-4711-af0d-f13379255c25">

所以这里是不是有问题？
https://github.com/Starry-OvO/aiotieba/blob/77ca7a08f5e541b0cabdd16b933cd209621b748f/thirdparty/rapidjson/internal/itoa.h#L35
原文件所属的rapidjson是一个C++项目，`inline`关键字的语义和C不同，用在C里可能导致编译器不内联，同时又没有外联版本，于是`undefined symbol`。这里应该改成`static inline char *u64toa`吧？
修改代码加上`static`后重新编译，这次生成的so可以正常导入了，而且运行也没有出现`Segmentation fault`。

奇怪的是我用`pip install`安装的`aiotieba`却没有这个问题，难道是`whl`文件用的编译器不一样？或者加了某些编译选项？

**Comment by n0099** [comment]
PR is welcome

**Comment by Hawaii-ol** [comment]
> PR is welcome

只改一个单词的问题，就当bug提了吧，不用提pr了

**Comment by lumina37** [comment]
我回家之后看看，很神奇的问题
不过我并没有调用libz啊，这是从哪里飞到libz去的

**Comment by Hawaii-ol** [comment]
> 我回家之后看看，很神奇的问题 不过我并没有调用libz啊，这是从哪里飞到libz去的

我大概猜到为什么了。报错位置是
https://github.com/Starry-OvO/aiotieba/blob/77ca7a08f5e541b0cabdd16b933cd209621b748f/aiotieba/helper/crypto/cuid.c#L70
因为libz里也有同名的crc32函数，构建WHL时链接到了libz里的crc32，而不是[crc32.c](https://github.com/Starry-OvO/aiotieba/blob/77ca7a08f5e541b0cabdd16b933cd209621b748f/thirdparty/crc/crc32.c)里的crc32。把`crc32.c`里的函数改名成`mycrc32`之类的或许能解决问题。

**Comment by lumina37** [comment]
怪了，我用ubuntu20.04安装PyPI的aiotieba3.4.1没有问题，直接`pip install .`编译安装develop分支也没有问题，windows重复上面两个步骤也没有问题，不应该是wheel的问题吧。

测试使用的脚本：

```python
import asyncio

import aiotieba as tb


async def main():
    async with tb.Client('default') as brow:
        print(brow.account.cuid_galaxy2)


asyncio.run(main())
```

我在unbuntu用`whereis`看了一下libz的位置也很常规`libz: /usr/lib/x86_64-linux-gnu/libz.a /usr/lib/x86_64-linux-gnu/libz.so`

要不试试`echo ${C_INCLUDE_PATH}`看看是不是环境变量的问题？不过libz的crc32.h是直接放在主目录下的没理由用`crc32/crc32.h`还能include到啊

**Comment by lumina37** [comment]
`static inline`相关的的那个奇妙bug我已经尝试修复了 64dd4b354ac26d6dbacd7c9dae150a5a8687d9cd

**Comment by Hawaii-ol** [comment]
```python
import asyncio

import aiotieba as tb


async def main():
    async with tb.Client('default') as brow:
        print(brow.account.cuid_galaxy2)


asyncio.run(main())
```
这个脚本只是测试`cuid_galaxy2`能不能导入啊，并没有调用它。问题是在调用这个函数时出现的，因为这个函数调用了`tbc_heliosHash`，而`tbc_heliosHash`又调用了`crc32`。

我用`pip install aiotieba`显示抓取的是`aiotieba-3.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`这个文件。我从Releases里直接下载解压这个文件得到`aiotieba`文件夹，用下面的代码测试一样得到`Segmentation fault`
```python
from aiotieba.helper.crypto import cuid_galaxy2

if __name__ == '__main__':
    android_id = 'fb311262fa82f119'
    print(cuid_galaxy2(android_id))
```
<img width="267" alt="屏幕截图 2023-06-05 212656" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/6246c75a-82f8-452c-8b26-1f886b8bb155">


---

`#include "crc32/crc32.h"`的确包含的是项目里的`crc32.h`头文件，问题出在链接的时候。链接器可以同时看到两个名为`crc32`的符号，一个是`libz`里的，一个是`crc32.o`里的，编译wheel时由于某种原因它先看到的是`libz.so.1`，所以选择了其中的crc32而导致了错误。
这是wheel中的so文件中的`crc32`符号的解析结果，可以看到它来自`/lib/x86_64-linux-gnu/libz.so.1`
<img width="419" alt="屏幕截图 2023-06-05 211934" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/dc43300d-df97-4b73-ab8a-0af844786a1e">


而这是源码编译的正确的so中的`crc32`的解析结果，可以看到它来自`thirdparty/crc/crc32.c:48`
<img width="742" alt="屏幕截图 2023-06-05 212251" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/a2eb8e35-67c5-42d2-8078-bbe7d508ea0e">

解决冲突的最简单方式就是把`thirdparty/crc/crc32.c`中的`crc32`改个名字。

**Comment by Hawaii-ol** [comment]
> `static inline`相关的的那个奇妙bug我已经尝试修复了 [64dd4b3](https://github.com/Starry-OvO/aiotieba/commit/64dd4b354ac26d6dbacd7c9dae150a5a8687d9cd)

另外上面还有一行。。:joy:
https://github.com/Starry-OvO/aiotieba/blob/77ca7a08f5e541b0cabdd16b933cd209621b748f/thirdparty/rapidjson/internal/itoa.h#L19

**Comment by lumina37** [comment]
我明天花时间重构一下，涨知识了

**Comment by Hawaii-ol** [comment]
> 我明天花时间重构一下，涨知识了

大佬辛苦了

**Comment by lumina37** [comment]
#127 应该修复了

**Comment by Hawaii-ol** [comment]
> #127 应该修复了

有最新的whl文件吗，我重新测试一下

**Comment by lumina37** [comment]
这里https://test.pypi.org/project/aiotieba/3.4.3/

**Comment by Hawaii-ol** [comment]
感谢！现在wheel里的so已经可以正常工作了，函数名改成了`tbc_crc32`
<img width="702" alt="屏幕截图 2023-06-06 140932" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/e81b3b22-cb69-43f3-aa3c-d005acfba9bc">

源码编译也没有undefined symbol问题了
<img width="831" alt="屏幕截图 2023-06-06 142421" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/642df9e7-db00-442e-b94e-b321477063e1">


大佬效率就是高:+1:

另外源码编译时报了很多`unused parameter 'self'`的警告，可以考虑加`__attribute__ ((unused))`消除一下

**Comment by lumina37** [comment]
原来gcc还有这功能，又涨知识了
另外`python setup.py build_ext -i`可以原地编译，不用再额外copy
