### ISSUE TITLE
请教一个旧版的问题

### ISSUE THREAD

**Issue by Hawaii-ol** [Starry-OvO/Tieba-Cloud-Review#128]
v2.10.3版本的[`get_homepage`](https://github.com/Starry-OvO/aiotieba/blob/4fba4b58c4b1e98c11e198f832f62827dab5b539/aiotieba/client/get_homepage/_classdef.py)接口无法获取到用户的IP归属地信息，返回的字段为空，但是[`get_post`](https://github.com/Starry-OvO/aiotieba/blob/4fba4b58c4b1e98c11e198f832f62827dab5b539/aiotieba/client/get_posts/_classdef.py)接口可以，是什么原因呢？
我对比了一下v2.10.3和当前版本的`get_homepage`目录的proto文件，几乎是一样的，那么是请求参数的问题吗？
我又对比了一下二者的[`pack_proto`](https://github.com/Starry-OvO/aiotieba/blob/4fba4b58c4b1e98c11e198f832f62827dab5b539/aiotieba/client/get_homepage/_api.py#L12)方法，的确有一些区别，但我不确定具体是哪个字段的影响。

**Comment by lumina37** [comment]
估计是那个版本常数的问题，12.37之后才会带ip

**Comment by n0099** [comment]
对于主题帖/回复贴/楼中楼3大接口中附带的用户信息的ip归属地是22年5月的`12.23.7.0`引入的https://github.com/n0099/tbclient.protobuf/commit/7c0587a8e7910c2dc5a1f7913877d6d573356f67#diff-0cd18a13f37b1fa7a00bee09d6e54617331834d09725d5e5f3fe90f6306f63e0R170

**Comment by Hawaii-ol** [comment]
v2.10.3中的[`User.proto`](https://github.com/Starry-OvO/aiotieba/blob/4fba4b58c4b1e98c11e198f832f62827dab5b539/aiotieba/client/_protobuf/User.proto)文件是有`ip_address`字段的
我用现在的`pack_proto`方法替换掉v2.10.3中的，就可以返回IP了
我对比了一下二者的请求proto字段：
<img width="342" alt="屏幕截图 2023-06-11 095411" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/894c3b01-8579-4113-afbc-d25fb7f0d221">
<img width="342" alt="屏幕截图 2023-06-11 095711" src="https://github.com/Starry-OvO/aiotieba/assets/33550949/d412c8d5-0ceb-41f2-a165-44dd7d350b66">
发现只要带上`_client_type=2`就可以了（不过这个参数是什么意思呢？）
再次感谢各位！我关闭这个issue了

**Comment by lumina37** [comment]
可能是在那个版本之后才修复了`_client_type`缺失导致的一系列问题。当时贴吧后端暗改，对所有不带`_client_type`的请求都只返回适配远古版本的内容。这个参数具体是什么意思我也不懂，估计是安卓IOS的区别吧

**Comment by n0099** [comment]
那就是2022年12月31日前后的那次贴吧后端修改：
https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368179653
> 4\. json格式的这个接口中有一个遗留的冗余父主题帖元数据嵌套于`/.thread.thread_info`（`/.thread`本身就是回复贴的父主题帖元数据）中，他有一个`phone_type`，其值跟在贴吧网页端上才能看到的每个回复贴楼主使用的发帖设备（`来自Android/iPhone/Windows Phone/Windows 8 UWP客户端`，也就是经典发帖接口的`_client_type`字段值： [MoeNetwork/wmzz_post@`4752b09`/wmzz_post_cron.php#L16](https://github.com/MoeNetwork/wmzz_post/blob/4752b09ea53064be6a8f9b2cba842fa081ec75cc/wmzz_post_cron.php#L16) [MoeNetwork/wmzz_post@`80aba25`/wmzz_post_setting.php#L64](https://github.com/MoeNetwork/wmzz_post/blob/80aba25de46f5b2cb1a15aa2a69b527a7374ffa9/wmzz_post_setting.php#L64) ，以及更加远古的`来自百度相册`）相同（`android` `iphone`）

https://github.com/MoeNetwork/wmzz_post/blob/80aba25de46f5b2cb1a15aa2a69b527a7374ffa9/wmzz_post_setting.php#L64
```html
<option value="4" <?php if($s['device'] == '4') echo 'selected' ?> >Windows 8</option>
<option value="3" <?php if($s['device'] == '3') echo 'selected' ?> >Windows Phone</option>
<option value="2" <?php if($s['device'] == '2') echo 'selected' ?> >Android</option>
<option value="1" <?php if($s['device'] == '1') echo 'selected' ?> >iPhone</option>
```

https://github.com/Starry-OvO/aiotieba/issues/67#issuecomment-1376006123
> [`v2.10.2` (release)](https://github.com/Starry-OvO/aiotieba/releases/tag/v2.10.2) 中进一步指出：
> 
> > #67 #68 描述的bug的产生原因是 /pb/page 接口新增了对 _client_type 参数的依赖，缺失该参数会导致获取的数据归属于默认的远古版本，表现出的具体特征有: 返回用户昵称为旧版， user_list 不包含数据，无法识别音频内容等。因此在添加上 _client_type 参数后， 2.10.1 的以下变化可以被安全地回滚: FragImage.big_src 被重新添加， FragLink.is_external 恢复由 /mo/q/checkurl 前缀判断， Posts 和 Threads 的解析流程仅保留【同时使用 user_list + author_id 字段】而弃用【直接使用 author 字段】
> 
> 所以带个`_client_type=2`就可以变回user_list结构了？
