### ISSUE TITLE
运行删除历史帖子，报错

### ISSUE THREAD

**Issue by ningsibuqu** [Starry-OvO/Tieba-Cloud-Review#142]
```
import asyncio

import aiotieba as tb


async def main() -> None:
    async with tb.Client('default') as client:
        while posts_list := await client.get_self_posts():
            await asyncio.gather(*[client.del_post(post.fid, post.tid, post.pid) for posts in posts_list for post in posts])


asyncio.run(main())
```
<2023-08-24 13:00:30.570> [WARN] [get_self_posts] voice_info. user_id=xxxxxx

无后续

**Comment by lumina37** [comment]
我正在出差，得明天晚上回去才能处理了

**Comment by n0099** [comment]
https://github.com/rmb122/delete-my-history-in-tieba/issues/33

**Comment by ningsibuqu** [comment]
> [rmb122/delete-my-history-in-tieba#33](https://github.com/rmb122/delete-my-history-in-tieba/issues/33)

啥意思大佬

**Comment by lumina37** [comment]
修复了，更新到3.7.1就能解决问题

**Comment by ningsibuqu** [comment]
> 修复了，更新到3.7.1就能解决问题

谢谢，不过还没有检测到更新，等等我再试一下。
pip install --upgrade aiotieba

**Comment by ningsibuqu** [comment]
> 修复了，更新到3.7.1就能解决问题

![image](https://github.com/Starry-OvO/aiotieba/assets/51028975/43cfa950-c584-4814-88c9-ed47bb123155)
一直循环这两个贴子（贴子已经不见了），贴吧 APP 看 贴子还有 127

**Comment by lumina37** [comment]
这帖子有点早了，你可能得手动改一下页码跳过

**Comment by ningsibuqu** [comment]
这个可以有教程吗？完全不懂… 如果方便的话，谢谢了

Starry ***@***.***>于2023年8月26日 周六上午7:18写道：

**Comment by lumina37** [comment]
`client.get_self_posts()`那里加个页码参数变成`client.get_self_posts(1)`，发现一直在删同一条回复时可以再改成2。贴吧服务端是比较神奇

**Comment by ningsibuqu** [comment]
> `client.get_self_posts()`那里加个页码参数变成`client.get_self_posts(1)`，发现一直在删同一条回复时可以再改成2。贴吧服务端是比较神奇
![image](https://github.com/Starry-OvO/aiotieba/assets/51028975/b93ab0cc-213b-4d34-8a2b-81a07ee5a0a8)

改完2后运行无反应，不知道是不是删完了？

**Comment by lumina37** [comment]
那就是删不动了，手删应该也是一样的
