### ISSUE TITLE
关于 get_image 接口，没必要使用 numpy 和 opencv

### ISSUE THREAD

**Issue by zaw007** [Starry-OvO/Tieba-Cloud-Review#145]
百度接口返回的已经是图片的 bytes 数据，可以直接使用，没必要后续通过 opencv 转换为 ndarray，如果后续需要处理图片，应该自己安装模块，而不是在 aiotieba 中引入。我搜了下，只有这个接口需要使用这两个模块，为了使用这个接口还需要额外安装 numpy 和 opencv，有点麻烦，建议 parse_body 直接 return body，不进行 decode，移除相关引用。

**Comment by lumina37** [comment]
我准备下个版本加个`get_image_bytes`接口用来获取原始jpeg字节流
