### ISSUE TITLE
有没有群

### ISSUE THREAD

**Issue by runcrawlers** [Starry-OvO/Tieba-Cloud-Review#148]
有没有群

**Comment by lumina37** [comment]
并没有

**Comment by adk23333** [comment]
> 并没有

或许可以开一下github的disscussion栏，有些关于交流如何使用的问题确实不应该在issue里面

**Comment by n0099** [comment]
什么 https://github.com/Starry-OvO/aiotieba-reviewer/issues/15 https://github.com/Starry-OvO/aiotieba-reviewer/issues/28 #158
https://github.com/search?q=owner%3AStarry-OvO+involves%3Aadk23333&type=issues 有真相
