### ISSUE TITLE
可否将所有数据类型的基类换为pydantic库的basemodel

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/Tieba-Cloud-Review#150]
[Pydantic](https://docs.pydantic.dev/latest/)

这将极大的方便后续的开发工作中对于数据的处理

**Comment by lumina37** [comment]
我还得花时间研究一下这个库，不知道什么时候会有空

**Comment by adk23333** [comment]
> 我还得花时间研究一下这个库，不知道什么时候会有空

嗯，好的

**Comment by lumina37** [comment]
我看了一下，感觉不太行，像`yarl.URL`这种类型没法简便地序列化，而且贴吧这个后端格式也是抽象得离谱，这也是我没用`dataclasses`的原因

**Comment by adk23333** [comment]
> 我看了一下，感觉不太行，像`yarl.URL`这种类型没法简便地序列化，而且贴吧这个后端格式也是抽象得离谱，这也是我没用`dataclasses`的原因

如果要用的话，好像`yarl.URL`得自己继承pydantic的[HttpUrl](https://docs.pydantic.dev/2.1/usage/types/urls/)类来实现一个差不多的。贴吧的返回格式，看你typing模块部分那么多文件就能感受到了hh

**Comment by lumina37** [comment]
aiohttp的类型检查可不是按鸭子类型来的，所以自己实现`URL`肯定行不通

**Comment by n0099** [comment]
> [...]这也是我没用`dataclasses`的原因

https://github.com/Starry-OvO/aiotieba/commit/64ab7b048f955a01503303b791f87b8113f805af
https://github.com/Starry-OvO/aiotieba/compare/58d06654e713df0e8351841e6982851d782d8ff7~1...a65cde712c836f2b9ca34a3ba2cedfeceb02a9af
https://github.com/Starry-OvO/aiotieba/commit/bc0cff519b25457789d00938b207214a473035f3
