### ISSUE TITLE
楼中楼回复对象信息

### ISSUE THREAD

**Issue by Gong-air** [Starry-OvO/Tieba-Cloud-Review#151]
**我需要什么功能**
楼中楼里 
A 回复 B: “text” 
除了user A和text文本的信息，还有回复对象B的名称信息，不知道能否获取

感谢~

**Comment by n0099** [comment]
那就是个`@B`fragment有百度uid

**Comment by lumina37** [comment]
`Comment.reply_to_id`就是被回复人的uid。名称的话，因为贴吧楼中楼回复偶尔会炸，而且`show_name`一般也没p用，所以就没解析

**Comment by Gong-air** [comment]
谢谢，uid已经足够了~
