### ISSUE TITLE
添加在代码中给client传入配置的参数

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/Tieba-Cloud-Review#157]
目前我如果需要动态的调整客户端的配置的话，只能这样子？：
```python
async with aiotieba.Client("TopAdmin") as client:
            client.account.BDUSS = rqt.form.get('BDUSS')
            client.account.STOKEN = rqt.form.get('STOKEN')
            user = await client.get_self_info()
```
这很不方便

如果可以动态传入的话，我的管理器也可以将这些配置放入数据库内了

**Comment by lumina37** [comment]
这个我准备在4.0改进一下，我现在感觉外挂一个配置文件有点丑陋，4.0大概会改成直接传入BDUSS的方法，而不是用现在的key-value

**Comment by adk23333** [comment]
> 这个我准备在4.0改进一下，我现在感觉外挂一个配置文件有点丑陋，4.0大概会改成直接传入BDUSS的方法，而不是用现在的key-value

作为引入库的话，使用配置文件传参的确不方便hh

目前像我这样传的话，会不会有什么问题，我没仔细看完aiotieba的源码

**Comment by lumina37** [comment]
一般来说没什么问题，毕竟同一台机换账号也不会刷新cuid

**Comment by lumina37** [comment]
目前4.0的`Client`大概长这样

https://github.com/Starry-OvO/aiotieba/blob/89349de6fb052f8c1ed923f5fa1ce014527348b2/aiotieba/client.py#L145-L152

可以直接输入`BDUSS`初始化，或者如果还想自定义`STOKEN`或者`cuid`等参数就传个`Account`进去
你有没有什么改进的想法

**Comment by adk23333** [comment]
> 可以直接输入`BDUSS`初始化，或者如果还想自定义`STOKEN`或者`cuid`等参数就传个`Account`进去 你有没有什么改进的想法

没什么问题，不过我觉得STOKEN可以直接放参数里，以及这个BDUSS、STOKEN、Account三个参数还是分开吧，默认不需要填参数名的是BDUSS和STOKEN，规定Account必须使用参数名传入

[我重写的reviewer](https://github.com/adk23333/tieba-admin/tree/main/tieba-admin-server/plugins/review)
可以帮忙看看有没有什么问题吗

**Comment by lumina37** [comment]
但是绝大多数情况下都只需要一个BDUSS，所以我把STOKEN和其他参数都放到Account里去了，以后还需要加参数的话就在Account里加。不过account确实应该是kw-only。我待会要出去玩，晚上再看

**Comment by lumina37** [comment]
现在改成这样了

https://github.com/Starry-OvO/aiotieba/blob/f13edade5c277e084dcc1f99d58dff8bcb6d1ef8/aiotieba/client.py#L147-L157

**Comment by adk23333** [comment]
> https://github.com/Starry-OvO/aiotieba/blob/f13edade5c277e084dcc1f99d58dff8bcb6d1ef8/aiotieba/client.py#L147-L157

可以，正式发布4.0我就关issue了

**Comment by lumina37** [comment]
> > 可以直接输入`BDUSS`初始化，或者如果还想自定义`STOKEN`或者`cuid`等参数就传个`Account`进去 你有没有什么改进的想法
> 
> 没什么问题，不过我觉得STOKEN可以直接放参数里，以及这个BDUSS、STOKEN、Account三个参数还是分开吧，默认不需要填参数名的是BDUSS和STOKEN，规定Account必须使用参数名传入
> 
> [我重写的reviewer](https://github.com/adk23333/tieba-admin/tree/main/tieba-admin-server/plugins/review) 可以帮忙看看有没有什么问题吗

我只看了缓存部分，应该是没啥问题

**Comment by adk23333** [comment]
> 我只看了缓存部分，应该是没啥问题

嗯，实际使用中，对于那些特别多回复的老帖子，如水楼，是怎么处理的，全部录一遍相当费时间啊。

**Comment by lumina37** [comment]
老帖和其他帖不做区分，都只获取最后一页。水楼直接在获取的时候（producer阶段）就过滤掉

**Comment by adk23333** [comment]
> 老帖和其他帖不做区分，都只获取最后一页。水楼直接在获取的时候（producer阶段）就过滤掉

这样啊，我是获取全部页面了，怪不得
