### ISSUE TITLE
部分帖子会出现某一页请求超出范围的问题，但实际上后面还有楼层

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/Tieba-Cloud-Review#158]
复现可用如下代码

`await client.get_posts(3669356387, 44)`
报错如下
`<2024-01-28 17:32:45.457> [WARN] [get_posts] list assignment index out of range. tid=3669356387`

而43页的has_more是true的，44页本身has_more则是false，然后45页可以请求到有内容，直至帖子结束。

在贴吧app上，在该楼内往下拉，直到正序43页最后一楼或者倒序45页第一楼的楼层后就会无法加载后续的楼层
在网页版则是这些楼层之间缺了一大片楼层。

吧和帖子可以由以上post获取了，就不发了
目前只在该贴遇到此问题

应该是官方的问题？

**Comment by lumina37** [comment]
不知道为什么这一页完全没有任何信息，包括`page.total_page`。我觉得应该是官方的问题，可能一整页都被删了就会出现这种情况

**Comment by adk23333** [comment]
> 不知道为什么这一页完全没有任何信息，包括`page.total_page`。我觉得应该是官方的问题，可能一整页都被删了就会出现这种情况

说实话，一删删整页是非常难以理解的，楼层和楼层之间一般都没什么联系。不过这个帖子是水贴，或许谁真的发了一片违规内容的楼层。。。

可以创建一个有很多楼的帖子，然后删掉一整页的楼层试试复现。

还有这种情况下，has_more其实并不准确了，最准确的遍历整个楼层的方法只能是一开始使用total_page了

**Comment by n0099** [comment]
`rn`多少？
https://github.com/Starry-OvO/aiotieba/blob/96ffd607efd0c068bc6af04017c24bc95dd182ed/aiotieba/client.py#L398
而网页端也是`30` F12-Console `$('.l_post').length`有真相

> 在网页版则是这些楼层之间缺了一大片楼层。

https://tieba.baidu.com/p/3669356387 `960回复贴，共31页`
最新回复贴[1015Lpid149147705471](https://tieba.baidu.com/p/3669356387?pid=149147705471#149147705471)  `1015/30=33.83...`
所以哪来的`pn=44`？
不过注意到[`pn=29`](https://tieba.baidu.com/p/3669356387?pn=29)只有14个回复贴而[`pn=30`](https://tieba.baidu.com/p/3669356387?pn=30)只有1个，这类分页错误在16年挺常见
显然贴吧不想用[cursor/keyset pagination](https://hn.algolia.com/?query=cursor+pagination)坚守[offset pagination](https://use-the-index-luke.com/no-offset) https://github.com/n0099/open-tbm/issues/24 而为了优化性能提前生成了每页有哪些pid而当年有些pid被删（亦或当年的另一套[主客态](https://en.wikipedia.org/wiki/Shadow_banning)早期实现如18年时引入的[`fold`](https://github.com/Starry-OvO/aiotieba/issues/123#issuecomment-1554505671)）后没有更新缓存至今

> 最准确的遍历整个楼层的方法只能是一开始使用total_page了

`pn=1`的`page.total_page`

**Comment by adk23333** [comment]
> 所以哪来的`pn=44`？ 

我说的pn仅对于aiotieba内设置rn=30而言，网页端我说的是**楼层**了，不是页码

**Comment by n0099** [comment]
> 最新回复贴[1015Lpid149147705471](https://tieba.baidu.com/p/3669356387?pid=149147705471#149147705471) `1015/30=33.83...`

就算`1~1015L`是连续的中间没有被删在`rn=30`下也只有至多[`CEIL()`](https://en.wikipedia.org/wiki/Floor_and_ceiling_functions)到34页

另外像这种以前的贴吧~bug~feature您也可以致电`05年起贴吧客户端内测用户老id吃miss吧候补吧主云南贵族`[556神](https://tieba.baidu.com/home/main?id=tb.1.d2a30a1d.z5JhlmRcd0xIN7onhFiZHw) https://z.n0099.net/#narrow/near/70909 https://tieba.baidu.com/p/8813888428?pid=149432733310#149432733310 亦或[`bug吧`](https://tieba.baiduc.com/bug)`常委武汉台大EE`[昌维](https://tieba.baidu.com/home/main/?id=tb.1.3cc830b7.o23W5SWssabO5EZvE1w9Pw) https://z.n0099.net/#narrow/near/79467 https://twitter.com/changwei1006/status/1749870820309258745
