### ISSUE TITLE
某知名kotlin jetpack compose ui第三方去广告贴吧客户端`TiebaLite`疑似被百度橄榄

### ISSUE THREAD

**Issue by n0099** [Starry-OvO/Tieba-Cloud-Review#168]
https://web.archive.org/web/20240217185947/https://github.com/HuanCheng65/TiebaLite
https://web.archive.org/web/20240217193136/https://github.com/HuanCheng65/TiebaLite/commit/2e9ba2b09d59967f36faf9fad84ab318c4786aef
https://web.archive.org/web/20240217192938/https://github.com/HuanCheng65/TiebaLite/commit/b2108d59eecd8878f31e92a2ad412304125050bf
```diff
## 👋再见

亲爱的朋友们：

我之所以写下这些文字，是因为我已经做出了一个艰难的决定——永久停止对贴吧 Lite 的维护。这个决定并非一蹴而就，而是经过深思熟虑、反复权衡之后的结果。

首先，最主要的原因是个人精力的限制。随着学业压力的增加，我发现自己越来越难以分配足够的时间和精力来维持项目所需的持续投入。项目的维护不仅仅是时间的问题，更是一个精力的挑战，需要我不断地更新、解决问题，这成为了我越来越难以克服的障碍。此外，尽管这绝非决定性的原因，但项目存在的合规性问题也为我带来了额外的顾虑，这些顾虑随时间积累，最终对我的决定产生了一定影响。

-在过去的四年中，我与贴吧 Lite 一同成长。因此，作出这一决定，我的内心充满了不舍。在此，我想向所有关注、使用和支持贴吧 Lite 的朋友们表达我的深深感谢。正是你们的反馈、建议和鼓励，让我在过去的岁月里不断前进，持续成长。
+在过去的四年中，我与贴吧 Lite 一同成长。因此，作出这一决定，我的内心充满了不舍。在此，我想向所有关注、使用和支持贴吧 Lite 的朋友们表达我的深深感谢。正是你们的反馈、建议和鼓励，让我在过去的岁月里不断前进，持续成长。同时，我也要特别感谢那些在过去几年中向开源仓库中贡献过代码的其他开发者们，是你们的努力，让贴吧 Lite 不断变得更好。

-宇宙很大，生活更大。我们的路径仍有可能在未来的某个时刻再次交汇。❤️
+宇宙很大，生活更大。相信今后我们的路径仍有可能在未来的某个时刻再次交汇。❤️

幻城

2024年2月18日
```
https://web.archive.org/web/20240217195158/https://t.me/tblite_discuss 暂且还在但我看不到里面
https://github.com/n0099/archive-TiebaLite `git clone`伪fork以避免被某人正义`DMCAtakedown` https://github.com/search?q=repo%3Agithub%2Fdmca+baidu&type=code 时一锅端所有202个fork https://web.archive.org/web/20240217195211/https://github.com/HuanCheng65/TiebaLite/network/members https://web.archive.org/web/20240217195301/https://github.com/HuanCheng65/TiebaLite/network 正如同 @BANKA2017 https://twitter.com/manka_takami/status/1746472845977460923 的 https://web.archive.org/web/20240217200441/https://github.com/bankaallbackup

# [当前事件](https://github.com/ESUAdmin/esu/blob/8f07c4ea48572d29e70949ddb98c905e669351bc/%E9%94%A1%E5%85%B0%C2%B7%E5%8B%92%E5%AD%94%E7%89%B9.html#L114)
## 截至2024年02月，每天都会成为昨天，记载的内容可能[在三分钟内死亡](https://web.archive.org/web/20240218074706/https://htmlpreview.github.io/?https://github.com/Xiaozhan-sb/ESU-HTML-Archive/blob/master/html/%E6%96%87%E9%9B%86/%E3%80%8A%E8%AE%BA%E8%83%8C%E5%AE%88%E6%89%BF%E8%AF%BA%E6%97%B6%E4%BB%87%E4%BA%BA%E8%A3%82%E5%8F%98%E7%AE%97%E8%AE%A1%E8%B0%8B%E6%9D%80%E8%AF%B4_%EF%BD%9E_%E5%A4%B1%E5%8E%BB%E4%BA%BA%E5%BD%A2%E5%9C%B0%E7%8B%B1%E8%BD%AE%E5%9B%9E%E7%AF%87%E3%80%8B.html)。

**Comment by lumina37** [comment]
脱坑挺好的，远离垃圾平台和kpi官方

**Comment by n0099** [comment]
https://web.archive.org/web/20240218141928/https://t.me/s/tblite/98
https://web.archive.org/web/20240218142743/https://t.me/s/tblite

**Comment by kokoro-aya** [comment]
Even YouTube has a history of banning ad-free plugins so it won't be surprising to see Chinese companies chasing down ad-free clients.

**Comment by n0099** [comment]
https://web.archive.org/web/20240221094003/https://github.com/HuanCheng65/huancheng65.github.io/commits/master/
https://web.archive.org/web/20240221093425/https://github.com/HuanCheng65/huancheng65.github.io/commit/b43ae151039aaec3fb97fd399c230c275afc0b6e
https://web.archive.org/web/20240221093545/https://huancheng65.github.io/

**Comment by n0099** [comment]
https://github.com/mattduck/gh2md
https://github.com/n0099/archive-TiebaLite/commit/5f65e256d7170a785351ae6e208dea08a35c4d2c
但没有[github discussions](https://docs.github.com/en/discussions)可能因为[archive repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)会自动[关闭discussions区](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository)亦或 https://github.com/HuanCheng65 在archive前手动关闭了

**Comment by n0099** [comment]
某fork https://github.com/zzc10086/TiebaLite

**Comment by n0099** [comment]
截止2026年6月 https://useful-forks.github.io/?repo=HuanCheng65%2FTiebaLite TiebaLite不但不会灭亡，反而会蒸蒸日上

**Comment by n0099** [comment]
```sh
(
head -n1 useful-forks-HuanCheng65_TiebaLite.csv;
sort -t, -rk7 useful-forks-HuanCheng65_TiebaLite.csv |
  awk -F, '
    BEGIN {OFS=FS} # https://unix.stackexchange.com/questions/136322/how-to-replace-the-content-of-a-specific-column-with-awk/404821\#404821 \
    match($5, /"([0-9]+)"/, ahead) \
    match($6, /"([0-9]+)"/, behind) {
      if (ahead[1] > 1 && behind[1] != 784) {
        match($1, /"(.+)"/, fork);
        split(fork[1], fork_repo_user, "/")
        $6="\""behind[1]"<br>["fork_repo_user[1]":HEAD...HuanCheng65/HEAD](https://github.com/"fork[1]"/compare/HEAD...HuanCheng65:TiebaLite:HEAD)\"";
        sub("/", ":", fork[1])
        $5="\""ahead[1]"<br>[HuanCheng65/4.0-dev..."fork_repo_user[1]":HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev..."fork[1]":HEAD)\"";
        print
     }
   }'
) | cut -f2- -d,
```
behind 784 commits的是指fork repo的default branch不是[`upstream/rm`](https://github.com/HuanCheng65/TiebaLite/commits/rm)如 https://github.com/jiangshuai218/TiebaLite/compare/master...HuanCheng65:TiebaLite:rm 而这类fork大多在branch `master`上没有区别 https://github.com/HuanCheng65/TiebaLite/compare/master...jiangshuai218:master ，但usefulforks只能diff repo之间的default branch https://github.com/HuanCheng65/TiebaLite/compare/rm...jiangshuai218:master 所以他们大多ahead 2/6 commits因而需要排除
|URL                                       |Stars|Forks|Ahead                                                                                                                                 |Behind                                                                                                                         |Last Push |
|------------------------------------------|-----|-----|--------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------|----------|
|https://github.com/seeyou-github/TiebaLite|0    |0    |29<br>[HuanCheng65/4.0-dev...seeyou-github:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...seeyou-github:TiebaLite:HEAD)|0<br>[seeyou-github:HEAD...HuanCheng65/HEAD](https://github.com/seeyou-github/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)|2026-06-20|
|https://github.com/Doddddd/TiebaLite      |1    |0    |4<br>[HuanCheng65/4.0-dev...Doddddd:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...Doddddd:TiebaLite:HEAD)          |0<br>[Doddddd:HEAD...HuanCheng65/HEAD](https://github.com/Doddddd/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)         |2026-06-20|
|https://github.com/Malus-risus/TiebaLite  |0    |0    |5<br>[HuanCheng65/4.0-dev...Malus-risus:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...Malus-risus:TiebaLite:HEAD)  |2<br>[Malus-risus:HEAD...HuanCheng65/HEAD](https://github.com/Malus-risus/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD) |2026-06-19|
|https://github.com/xiaoancute/TiebaLite   |1    |0    |59<br>[HuanCheng65/4.0-dev...xiaoancute:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...xiaoancute:TiebaLite:HEAD)   |5<br>[xiaoancute:HEAD...HuanCheng65/HEAD](https://github.com/xiaoancute/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)   |2026-06-17|
|https://github.com/0ranko0P/TiebaLite     |301  |6    |751<br>[HuanCheng65/4.0-dev...0ranko0P:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...0ranko0P:TiebaLite:HEAD)      |2<br>[0ranko0P:HEAD...HuanCheng65/HEAD](https://github.com/0ranko0P/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2026-06-13|
|https://github.com/zzc10086/TiebaLite     |2383 |72   |142<br>[HuanCheng65/4.0-dev...zzc10086:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...zzc10086:TiebaLite:HEAD)      |2<br>[zzc10086:HEAD...HuanCheng65/HEAD](https://github.com/zzc10086/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2026-06-11|
|https://github.com/aahowe/TiebaLite-Next  |0    |0    |3<br>[HuanCheng65/4.0-dev...aahowe:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...aahowe:TiebaLite-Next:HEAD)       |2<br>[aahowe:HEAD...HuanCheng65/HEAD](https://github.com/aahowe/TiebaLite-Next/compare/HEAD...HuanCheng65:TiebaLite:HEAD)      |2026-04-28|
|https://github.com/RyanZhou416/TiebaLite  |0    |0    |11<br>[HuanCheng65/4.0-dev...RyanZhou416:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...RyanZhou416:TiebaLite:HEAD) |2<br>[RyanZhou416:HEAD...HuanCheng65/HEAD](https://github.com/RyanZhou416/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD) |2026-04-23|
|https://github.com/AcE77505/TiebaLite     |0    |0    |22<br>[HuanCheng65/4.0-dev...AcE77505:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...AcE77505:TiebaLite:HEAD)       |14<br>[AcE77505:HEAD...HuanCheng65/HEAD](https://github.com/AcE77505/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)      |2026-04-08|
|https://github.com/Dystnine/TiebaLite     |0    |0    |4<br>[HuanCheng65/4.0-dev...Dystnine:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...Dystnine:TiebaLite:HEAD)        |19<br>[Dystnine:HEAD...HuanCheng65/HEAD](https://github.com/Dystnine/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)      |2026-03-22|
|https://github.com/GO-PIO/TiebaLite       |0    |0    |5<br>[HuanCheng65/4.0-dev...GO-PIO:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...GO-PIO:TiebaLite:HEAD)            |2<br>[GO-PIO:HEAD...HuanCheng65/HEAD](https://github.com/GO-PIO/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)           |2026-02-25|
|https://github.com/GO-PIO/TiebaLite       |0    |0    |5<br>[HuanCheng65/4.0-dev...GO-PIO:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...GO-PIO:TiebaLite:HEAD)            |2<br>[GO-PIO:HEAD...HuanCheng65/HEAD](https://github.com/GO-PIO/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)           |2026-02-25|
|https://github.com/hanakoNya/TiebaLite    |0    |0    |2<br>[HuanCheng65/4.0-dev...hanakoNya:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...hanakoNya:TiebaLite:HEAD)      |38<br>[hanakoNya:HEAD...HuanCheng65/HEAD](https://github.com/hanakoNya/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)    |2025-12-29|
|https://github.com/rhjdvsgsgks/TiebaLite  |0    |0    |12<br>[HuanCheng65/4.0-dev...rhjdvsgsgks:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...rhjdvsgsgks:TiebaLite:HEAD) |33<br>[rhjdvsgsgks:HEAD...HuanCheng65/HEAD](https://github.com/rhjdvsgsgks/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)|2025-11-25|
|https://github.com/rhjdvsgsgks/TiebaLite  |0    |0    |12<br>[HuanCheng65/4.0-dev...rhjdvsgsgks:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...rhjdvsgsgks:TiebaLite:HEAD) |33<br>[rhjdvsgsgks:HEAD...HuanCheng65/HEAD](https://github.com/rhjdvsgsgks/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)|2025-11-25|
|https://github.com/mytangyh/TiebaLite     |0    |0    |2<br>[HuanCheng65/4.0-dev...mytangyh:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...mytangyh:TiebaLite:HEAD)        |2<br>[mytangyh:HEAD...HuanCheng65/HEAD](https://github.com/mytangyh/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2025-10-12|
|https://github.com/kmcbest/TiebaLite      |0    |0    |5<br>[HuanCheng65/4.0-dev...kmcbest:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...kmcbest:TiebaLite:HEAD)          |64<br>[kmcbest:HEAD...HuanCheng65/HEAD](https://github.com/kmcbest/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)        |2025-09-16|
|https://github.com/qpst4/TiebaLite        |0    |0    |2<br>[HuanCheng65/4.0-dev...qpst4:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...qpst4:TiebaLite:HEAD)              |64<br>[qpst4:HEAD...HuanCheng65/HEAD](https://github.com/qpst4/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)            |2025-08-04|
|https://github.com/tapttr/TiebaLite       |0    |0    |2<br>[HuanCheng65/4.0-dev...tapttr:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...tapttr:TiebaLite:HEAD)            |90<br>[tapttr:HEAD...HuanCheng65/HEAD](https://github.com/tapttr/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)          |2025-05-03|
|https://github.com/lizc2333/TiebaLite     |0    |0    |3<br>[HuanCheng65/4.0-dev...lizc2333:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...lizc2333:TiebaLite:HEAD)        |2<br>[lizc2333:HEAD...HuanCheng65/HEAD](https://github.com/lizc2333/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2025-04-27|
|https://github.com/lizc2333/TiebaLite     |0    |0    |3<br>[HuanCheng65/4.0-dev...lizc2333:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...lizc2333:TiebaLite:HEAD)        |2<br>[lizc2333:HEAD...HuanCheng65/HEAD](https://github.com/lizc2333/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2025-04-27|
|https://github.com/devwian/TiebaLite      |0    |0    |5<br>[HuanCheng65/4.0-dev...devwian:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...devwian:TiebaLite:HEAD)          |2<br>[devwian:HEAD...HuanCheng65/HEAD](https://github.com/devwian/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)         |2025-02-05|
|https://github.com/LysergidsS/TiebaLite   |0    |0    |14<br>[HuanCheng65/4.0-dev...LysergidsS:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...LysergidsS:TiebaLite:HEAD)   |2<br>[LysergidsS:HEAD...HuanCheng65/HEAD](https://github.com/LysergidsS/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)   |2024-11-16|
|https://github.com/misaka36/TiebaLite     |0    |0    |2<br>[HuanCheng65/4.0-dev...misaka36:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...misaka36:TiebaLite:HEAD)        |2<br>[misaka36:HEAD...HuanCheng65/HEAD](https://github.com/misaka36/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2024-10-01|
|https://github.com/cyhycf/TiebaLite       |0    |0    |2<br>[HuanCheng65/4.0-dev...cyhycf:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...cyhycf:TiebaLite:HEAD)            |2<br>[cyhycf:HEAD...HuanCheng65/HEAD](https://github.com/cyhycf/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)           |2024-09-02|
|https://github.com/Phoneliu/TiebaLite     |0    |0    |3<br>[HuanCheng65/4.0-dev...Phoneliu:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...Phoneliu:TiebaLite:HEAD)        |2<br>[Phoneliu:HEAD...HuanCheng65/HEAD](https://github.com/Phoneliu/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2024-03-14|
|https://github.com/Phoneliu/TiebaLite     |0    |0    |3<br>[HuanCheng65/4.0-dev...Phoneliu:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...Phoneliu:TiebaLite:HEAD)        |2<br>[Phoneliu:HEAD...HuanCheng65/HEAD](https://github.com/Phoneliu/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)       |2024-03-14|
|**HuanCheng65's repo archived**|||||2024-02-17|
|https://github.com/huajiworld/TiebaLite   |0    |0    |2<br>[HuanCheng65/4.0-dev...huajiworld:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...huajiworld:TiebaLite:HEAD)    |463<br>[huajiworld:HEAD...HuanCheng65/HEAD](https://github.com/huajiworld/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD) |2023-01-09|
|https://github.com/RyensX/TiebaLitePlus   |1    |1    |4<br>[HuanCheng65/4.0-dev...RyensX:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...RyensX:TiebaLitePlus:HEAD)        |578<br>[RyensX:HEAD...HuanCheng65/HEAD](https://github.com/RyensX/TiebaLitePlus/compare/HEAD...HuanCheng65:TiebaLite:HEAD)     |2022-07-19|
|https://github.com/ShellWen/TiebaLite     |9    |1    |57<br>[HuanCheng65/4.0-dev...ShellWen:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...ShellWen:TiebaLite:HEAD)       |836<br>[ShellWen:HEAD...HuanCheng65/HEAD](https://github.com/ShellWen/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)     |2020-08-13|
|https://github.com/GoFly-wenxue/TiebaLite |0    |0    |7<br>[HuanCheng65/4.0-dev...GoFly-wenxue:HEAD](https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...GoFly-wenxue:TiebaLite:HEAD)|57<br>[GoFly-wenxue:HEAD...HuanCheng65/HEAD](https://github.com/GoFly-wenxue/TiebaLite/compare/HEAD...HuanCheng65:TiebaLite:HEAD)|2020-08-11|

**Comment by n0099** [comment]
~由于usefulforks不支持递归查fork的fork~实际上支持只是没在fork的upstream不是查询的repo时显示fork的upstream所以不好一眼区分
https://useful-forks.github.io/?repo=0ranko0P%2FTiebaLite
https://github.com/xiaoancute/TiebaLite

https://useful-forks.github.io/?repo=zzc10086%2FTiebaLite
https://github.com/seeyou-github/TiebaLite
https://github.com/AcE77505/TiebaLite

而且usefulforks上的ahead/behind链接指向的是`fork/HEAD...upstream/HEAD`（`HEAD` ref是指default branch）之diff如https://github.com/zzc10086/TiebaLite/compare/4.0-dev...seeyou-github:4.0-dev ，所以fork的fork（或者准确地说`fork的upstream不是查询的repo`）的ahead/behind链接跟上表（其只是简单的`fork/HEAD...HuanCheng65的repo/HEAD`）中的不同如 https://github.com/HuanCheng65/TiebaLite/compare/4.0-dev...seeyou-github:TiebaLite:HEAD

**Comment by n0099** [comment]
https://github.com/odlove/TiebaLite
https://github.com/odlove/tieba_lite

**Comment by n0099** [comment]
https://github.com/zzc10086/TiebaLite/issues/119#issuecomment-5513636325

https://github.com/min09577/TiebaLite 什么LLM带革命引路人
由于该repo不在`HuanCheng65/TiebaLite`的forks network中所以此前没有发现
快速搜索非fork repo https://github.com/search?q=tiebalite&type=repositories&s=updated
https://github.com/toamdou/TiebaLite-IOS
https://github.com/gudianxingkongmeng/TiebaLite-harmony
https://github.com/yyz0313/TiebaLite
https://github.com/xieyinch/tiebalite
https://github.com/ked33/TiebaLite

**Comment by n0099** [comment]
https://github.com/lumina37/aiotieba/issues/168#issuecomment-4760091767
> https://useful-forks.github.io/?repo=0ranko0P%2FTiebaLite

https://github.com/neveragain233/TiebaLite

---
https://github.com/lumina37/aiotieba/issues/168#issuecomment-5513843840
> [...]什么LLM带革命引路人

https://github.com/juersss/TiebaLite

**Comment by n0099** [comment]
不早于2026年3月31日 https://web.archive.org/web/20260331094626/https://github.com/HuanCheng65/TiebaLite `HuanCheng65/TiebaLite`业已取消archived repo并将default branch改回[`4.0-dev`](https://github.com/HuanCheng65/TiebaLite/tree/4.0-dev)

**Comment by n0099** [comment]
不是fork
https://github.com/infinityf4p/TiebaPure-iOS
https://github.com/infinityf4p/TiebaPure-Android

**Comment by n0099** [comment]
https://github.com/zzc10086/TiebaLite/issues/119#issuecomment-5660905028
> > > 找了半天没找到话题入口(笑
> > > 我刚刚试了试另一个更新的项目[min09577/TiebaLite](https://github.com/min09577/TiebaLite?rgh-link-date=2026-09-14T08%3A05%3A27.000Z)
> > > 发现这个最新的tiebalite版本只能显示话题排行，甚至已经点不进话题里面了。入口没了
> 
> 哥们 这个项目404了啊

> @min09577 好像号没了
