### ISSUE TITLE
我想请问一下有没有获得阅读量的功能

### ISSUE THREAD

**Issue by huangzhihao1** [Starry-OvO/Tieba-Cloud-Review#171]

**Comment by n0099** [comment]
主题帖的？
https://github.com/n0099/tbclient.protobuf/blame/e7825f56bf0ce23d528490f8e0a450c8c884929f/proto/ThreadInfo.proto#L74
https://github.com/search?q=repo%3An0099%2Fopen-tbm+viewCount&type=code

**Comment by lumina37** [comment]
这个？

https://github.com/Starry-OvO/aiotieba/blob/7551842c8a4e3fcb9ed63eb6f50da4ac4268e4a7/aiotieba/api/get_threads/_classdef.py#L564

简单demo

```python
import asyncio

import aiotieba


async def main():
    async with aiotieba.Client() as client:
        threads = await client.get_threads("天堂鸡汤")
        for thread in threads[3:6]:
            print(f"浏览量: {thread.view_num}")


asyncio.run(main())
```

**Comment by huangzhihao1** [comment]
感谢！已经解决
