### ISSUE TITLE
`get_self_posts`  是只能抓自己的回复吗？

### ISSUE THREAD

**Issue by Dilettante258** [Starry-OvO/Tieba-Cloud-Review#180]
我试着改了一下源代码，试试 `get_self_posts` 能不能抓别人的，但是返回数据的都是空的。

很好奇那些贴吧工具箱又是怎么抓取评论的。

**Comment by lumina37** [comment]
当然只能抓自己的。我也没搞懂那些工具箱是怎么查发言的，貌似高级搜索的接口已经被ban了

**Comment by Dilettante258** [comment]
好的，谢谢👌🙂

**Comment by lumina37** [comment]
下午受大佬点拨把这个接口的调用方法找出来了，其实就是改个版本号的事情https://github.com/Starry-OvO/aiotieba/commit/c6d370713e91918a0a17f822cf3f449936bb3b28

**Comment by Dilettante258** [comment]
麻烦啦。谢谢！🤩🤩🤩

**Comment by n0099** [comment]
> 我也没搞懂那些工具箱是怎么查发言的

https://www.82cat.com/tieba/reply/n0099/1

> 下午受大佬点拨把这个接口的调用方法找出来了

不二告诉您的？

**Comment by lumina37** [comment]
> > 我也没搞懂那些工具箱是怎么查发言的
> 
> https://www.82cat.com/tieba/reply/n0099/1
> 
> > 下午受大佬点拨把这个接口的调用方法找出来了
> 
> 不二告诉您的？

一个水友，反正不是站长

**Comment by n0099** [comment]
bug吧壬？小心明天接口就失效

**Comment by n0099** [comment]
> 貌似高级搜索的接口已经被ban了

19年esuwiki带流行
https://github.com/ESUAdmin/esu/blob/8f07c4ea48572d29e70949ddb98c905e669351bc/%E5%88%98%E6%85%88%E6%AC%A3.html#L383
https://github.com/ESUAdmin/esu/blob/8f07c4ea48572d29e70949ddb98c905e669351bc/%E5%88%98%E6%85%88%E6%AC%A3.html#L590
时关闭的网页高级搜索 https://tieba.baidu.com/f/search/res?ie=utf-8&qw=n0099 跟上面82工具盒的相比索引明显滞后很久

> 其实就是改个版本号的事情 https://github.com/Starry-OvO/aiotieba/commit/c6d370713e91918a0a17f822cf3f449936bb3b28

https://github.com/Starry-OvO/aiotieba/blob/c6d370713e91918a0a17f822cf3f449936bb3b28/aiotieba/api/get_user_contents/get_posts/_api.py#L10
我记得当年就有人在目录吧主群里声称某8.x版本客户端可以像高搜那样查用户全吧回复贴，但没说具体版本号多少
这就像吧首页主题帖接口用远古版本`6.0.2`才能看到unixtimestamp的最后回复时间一样
https://github.com/search?q=repo%3An0099%2Fopen-tbm+6.0.2&type=code
以及主题帖回复贴接口用`8.8.8.8`
https://github.com/n0099/open-tbm/blob/4f0745c64ba0b756e7e2a763b47c6e951c08e767/c%23/crawler/src/Tieba/Crawl/ThreadLateCrawlerAndSaver.cs#L44
看网页端上可见的`发帖客户端类型`
https://github.com/n0099/open-tbm/blob/4f0745c64ba0b756e7e2a763b47c6e951c08e767/c%23/crawler/src/Tieba/Crawl/ThreadLateCrawlerAndSaver.cs#L91
`_client_version` https://github.com/TRPGEngine/Server/blob/feb08996077c2473e4a65fc3a4de28ab11544483/services/tieba-helper/index.ts#L66-L69

**Comment by n0099** [comment]
> 貌似高级搜索的接口已经被ban了

在曾于18年7月主持[血小板吧事件](https://zhuanlan.zhihu.com/p/57239365)的某esu狗`妖照` [`实名/张钦瑞`](https://archive.md/a7iWY)于19年3月幕后主导的b吧事件 https://n0099.net/tbm/bilibiliVote https://moegirl.uk/User:A635683851/Bilibili吧吧务被警告及下台事件 https://web.archive.org/web/20220205061240/https://zh.moegirl.org.cn/User:A635683851/Bilibili吧吧务被警告及下台事件 有请时任esu调查员 @creeper9
及此后19年4月esuwiki出道刘慈欣
https://html-preview.github.io/?url=https://github.com/ESUAdmin/esu/blob/8f07c4ea48572d29e70949ddb98c905e669351bc/刘慈欣.html
https://github.com/ESUAdmin/esu/blob/8f07c4ea48572d29e70949ddb98c905e669351bc/刘慈欣.html#L383
https://github.com/ESUAdmin/esu/blob/8f07c4ea48572d29e70949ddb98c905e669351bc/刘慈欣.html#L590
时贴吧方面关闭的`网页高级搜索` https://tieba.baidu.com/f/search/res?ie=utf-8&qw=n0099 目前削弱的`高搜`跟上面`不二工具盒`的相比索引明显滞后很久

> 其实就是改个版本号的事情 https://github.com/Starry-OvO/aiotieba/commit/c6d370713e91918a0a17f822cf3f449936bb3b28

https://github.com/Starry-OvO/aiotieba/blob/c6d370713e91918a0a17f822cf3f449936bb3b28/aiotieba/api/get_user_contents/get_posts/_api.py#L10
我记得当年就有人在目录吧主群里声称`某8.x`版本客户端可以像`高搜`那样查用户全吧回复贴楼中楼，但没说具体版本号多少
这就像`吧首页主题帖接口`用远古版本`6.0.2`才能看到`unixtimestamp的最后回复时间`一样
https://github.com/search?q=repo%3An0099%2Fopen-tbm+6.0.2&type=code

以及`主题帖回复贴接口`用`8.8.8.8`
https://github.com/n0099/open-tbm/blob/4f0745c64ba0b756e7e2a763b47c6e951c08e767/c%23/crawler/src/Tieba/Crawl/ThreadLateCrawlerAndSaver.cs#L44
看网页端上可见的`发帖客户端类型`
https://github.com/n0099/open-tbm/blob/4f0745c64ba0b756e7e2a763b47c6e951c08e767/c%23/crawler/src/Tieba/Crawl/ThreadLateCrawlerAndSaver.cs#L91
`_client_type`
https://github.com/n0099/tbclient.protobuf/blob/e7825f56bf0ce23d528490f8e0a450c8c884929f/proto/CommonReq.proto#L4
https://github.com/TRPGEngine/Server/blob/feb08996077c2473e4a65fc3a4de28ab11544483/services/tieba-helper/index.ts#L66-L69

**Comment by n0099** [comment]
我顺着昨天出现的某`贴吧相关repo`star狂魔 @sansiny https://web.archive.org/web/20240328160640/https://github.com/sansiny?tab=stars https://z.n0099.net/#narrow/near/103195 找到了个 https://github.com/Dilettante258/tieba-tools/blob/0e66159533518c624f4262b8ea3da329bb6e55b9/src/api/post.ts#L20 https://tb.wang1m.cc/userpost/n0099/1 但其api后端不开源看起来是直接反代protobuf接口

**Comment by Dilettante258** [comment]
> 我顺着昨天出现的某`贴吧相关repo`star狂魔 @sansiny https://web.archive.org/web/20240328160640/https://github.com/sansiny?tab=stars https://z.n0099.net/#narrow/near/103195 找到了个 https://github.com/Dilettante258/tieba-tools/blob/0e66159533518c624f4262b8ea3da329bb6e55b9/src/api/post.ts#L20 https://tb.wang1m.cc/userpost/n0099/1 但其api后端不开源看起来是直接反代protobuf接口

这个就是我参考着叶灵大佬的aiotieba的接口写的。这个没有后端，protobuf序列化和反序列化都是通过js在前端完成的。api接口之所以需要反代是因为cors问题

**Comment by n0099** [comment]
那么`_client_version=8.9.8.5`在哪儿？

**Comment by Dilettante258** [comment]
> 那么`_client_version=8.9.8.5`在哪儿？

https://github.com/Dilettante258/tieba-tools/blob/0e66159533518c624f4262b8ea3da329bb6e55b9/src/api/ProtobufParser.ts#L16

```typescript
export function postReqSerialize(userId:number, pn:number): Promise<Buffer> {
  return new Promise((resolve) => {
    const Proto = root.lookupType("UserPostReqIdl");

    const payload = {
      data: {
        needContent: 1,
        userId: userId,
        pn: pn,
        common: {
          clientversion: "8.9.8.5",
        }
      }
    };

    const message = Proto.create(payload);
    const buffer = Proto.encode(message).finish();

    resolve(Buffer.from(buffer));
  });
}
```

**Comment by n0099** [comment]
`12.57.0.1`也能看到？

**Comment by Dilettante258** [comment]
> `12.57.0.1`也能看到？

不好意思，大早上还没醒，我复制错了。😹 已更改。
