### ISSUE TITLE
跟着入门教程运行例程的时候出现缺模块的错误

### ISSUE THREAD

**Issue by DentistCode** [Starry-OvO/Tieba-Cloud-Review#184]
### **简要描述这个bug**

报错代码
```
  File "C:\Users\XXX\Desktop\aiotieba\aiotieba\helper\crypto\__init__.py", line 3, in <module>
    from .crypto import c3_aid, cuid_galaxy2, rc4_42
ModuleNotFoundError: No module named 'aiotieba.helper.crypto.crypto'
```
---

### **如何复现**

跟着入门教程走

step1：
    git clone，并创建虚拟python环境

step2：
    `pip install aiotieba`

step3：
    运行样例代码
```
import asyncio
import aiotieba as tb
BDUSS = "balabala"

async def main():
    async with tb.Client(BDUSS) as client:
        user = await client.get_self_info()
    print(user)
asyncio.run(main())
```

step4：
报错
```
Traceback (most recent call last):
  File "D:\Downloads\aiotieba\aaa.py", line 4, in <module>
    import aiotieba as tb
  File "D:\Downloads\aiotieba\aiotieba\__init__.py", line 11, in <module>
    from . import const, core, enums, exception, logging, typing
  File "D:\Downloads\aiotieba\aiotieba\core\__init__.py", line 1, in <module>
    from .account import Account
  File "D:\Downloads\aiotieba\aiotieba\core\account.py", line 7, in <module>
    from ..helper import randbytes_nosec
  File "D:\Downloads\aiotieba\aiotieba\helper\__init__.py", line 1, in <module>
    from . import cache, crypto, utils
  File "D:\Downloads\aiotieba\aiotieba\helper\crypto\__init__.py", line 3, in <module>
    from .crypto import c3_aid, cuid_galaxy2, rc4_42
ModuleNotFoundError: No module named 'aiotieba.helper.crypto.crypto'
```

---

### **你希望程序作出何种行为**

...

### **截图（可选）**

...

### **我的尝试**

1. 定位模块位置。
定位到`aiotieba\helper\crypto\__init__.py` line3，直接运行`__init__.py`，出现`ImportError: attempted relative import with no known parent package`。即"尝试使用未知父包的相对导入"
2. 把相对位置改为绝对位置。
把相对导入`.crypto`修改成绝对导入`aiotieba.helper.crypto.crypto`，无果，同样的error。
3. 排除了python版本和环境网络的问题。
尝试了3.10、3.11、3.12，都同样报错。用了自己的小鸡，同样的问题。

第一次提issue，如有描述不当，敬请见谅。

已经RTFM，STFW，尝试用new bing搜索，没有类似问题。

**Comment by lumina37** [comment]
如果你的步骤是`git clone`这个repo，然后在项目文件夹里新建了一个py，再复制教程代码的话：python貌似会优先匹配本地的那个aiotieba文件夹而不是site-packages里面的那个。本地文件夹的./aiotieba/helper/crypto里是没有crypto.pyd的（这是一个需要编译的动态库），进而导致报错。

所以解决方法就是另开一个文件夹运行样例。

另外，即便使用`pip install -e .`从源码安装：scikit-build-core不会将编译好的pyd复制到./aiotieba/helper/crypto里，也会出现找不到包的错误。

**Comment by DentistCode** [comment]
已经成功了
原来如此，学到了很多，非常感谢
