### ISSUE TITLE
获得一个贴吧中各个分区的内容

### ISSUE THREAD

**Issue by Zhao-Yang88** [Starry-OvO/Tieba-Cloud-Review#191]
有没有办法能获得一个贴吧中各个分区的内容，现在好像只能获得精品贴

**Comment by lumina37** [comment]
目前没实现，我下个版本加上

**Comment by lumina37** [comment]
最近在准备MPEG开会的事，这个feature可能要等到4月25之后才能动手写了

**Comment by lumina37** [comment]
今天粗略研究了一下，这个获取分区下主题帖的接口和目前获取主题帖的接口不是同一个接口，而且需要传入的分区标识符不是人类可读的分区名而是分区的数字id，所以这个feature有一定概率不会在下个版本被加进来

**Comment by Dilettante258** [comment]
![image](https://github.com/Starry-OvO/aiotieba/assets/113875344/94a4bd6f-5c35-41bf-b4a3-ecb8c0c8a9cf)

分区的标识符指的是这个tabId吗？如果是根据吧名再指定分区的话，应该能够通过`/c/f/frs/page`接口反推出分区标识符。

**Comment by lumina37** [comment]
> 分区的标识符指的是这个tabId吗？如果是根据吧名再指定分区的话，应该能够通过`/c/f/frs/page`接口反推出分区标识符。

这个分区id不像精品分区id那样有个快速接口能查，塞个自动查询的调用进去副作用太大了

**Comment by Sorceresssis** [comment]
我也想问有没有可以查出一个帖子所在分区的方法。

**Comment by lumina37** [comment]
> 我也想问有没有可以查出一个帖子所在分区的方法。

好像没法，我们现在那个移动分区的指令是靠顶帖之后再抓主题帖列表来确定的分区
