### ISSUE TITLE
[WARN] Unknown fragment type. type=40 proto=type: 40

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/Tieba-Cloud-Review#192]
**简要描述这个bug**
无特别影响的WARN
贴吧客户端版本12.54.1.1
```
[2024-04-15 23:30:30 +0800] [22] [WARN] Unknown fragment type. type=40 proto=type: 40
text: "啊这"
link: "https://tieba.baidu.com/mo/q/hybrid-usergrow-search/searchGlobal?pageType=result&keyword=啊这&customfullscreen=1&nonavigationbar=1"
src: "https://tieba-ares.cdn.bcebos.com/mis/2023-11/1700620182255/378a4ca359a9.webp"
```

**如何复现**
在获取有热梗词的贴子上就会出现

**你希望程序作出何种行为**

...

**截图（可选）**

1. 楼层
![0abe57693ceaae107c1efb3599f9f2a](https://github.com/Starry-OvO/aiotieba/assets/84434845/9f10e733-2702-48a8-a842-2002efe8b47a)

2. 点击后的显示
![f5bddd66ba705f366d16fded7e646d7](https://github.com/Starry-OvO/aiotieba/assets/84434845/2196687c-d93e-414b-82ec-639550c4fff5)

**Comment by lumina37** [comment]
下个版本修复，准备解析成纯文本。什么官方梗百科

**Comment by adk23333** [comment]
> 什么官方梗百科

鉴定为贴吧烂活

**Comment by n0099** [comment]
内置了 https://github.com/itorr/nbnhhsh

**Comment by Voevodsky** [comment]
我就说咋回事，爬帖子内容的时候终端无限输出这条，加了logging.disable(logging.WARNING)去掉了

**Comment by lumina37** [comment]
修了 ee729d3235f233ae3b1c951cbc99648a4623218e 不过除了楼层回复，还会有别的地方刷出梗百科吗

**Comment by adk23333** [comment]
> 不过除了楼层回复，还会有别的地方刷出梗百科吗

![Screenshot_2024-04-17-10-11-30-039_com.baidu.tieba.png](https://github.com/Starry-OvO/aiotieba/assets/84434845/1a081988-3a9a-4e27-9b9f-73e03fe1c834)

主楼一楼也会

楼中楼还没见过

**Comment by lumina37** [comment]
标题里的貌似没影响

**Comment by adk23333** [comment]
> 标题里的貌似没影响

的确没有，警告的都是楼层

**Comment by n0099** [comment]
1L也是回复贴，远古时代可以只删1L而不删主题帖
就像回复贴也有`标题`且可以改 https://z.n0099.net/#narrow/near/98236
主题帖`标题`只是string而非pbcontent https://github.com/n0099/tbclient.protobuf/blame/e7825f56bf0ce23d528490f8e0a450c8c884929f/proto/ThreadInfo.proto#L72
