### ISSUE TITLE
[WARN] [get_bawu_postlogs] (302, 'Found'). args=('贴吧名',) kwargs={}

### ISSUE THREAD

**Issue by Voevodsky** [Starry-OvO/Tieba-Cloud-Review#193]
请问一下get_bawu_postlogs这个函数是能用的吗？我试了下获取的吧务帖子管理列表，一直返回

Postlogs(objs=[], page=Page_postlog(current_page=0, total_page=0, total_count=0, has_more=False, has_prev=False))

代码是这样的

async def main():
    async with aiotieba.Client(BDUSS) as client:
        bawu_info = await client.get_bawu_postlogs("贴吧名")
        print(bawu_info)
asyncio.run(main())

**Comment by lumina37** [comment]
现在大部分网页端接口（包括这个接口）都需要STOKEN，刚把注释加上了 a698e13289e2b6c44736b6562333b034362da9e5

**Comment by Voevodsky** [comment]
解决了，感谢
