### ISSUE TITLE
FragVoice的md5值是错误的！

### ISSUE THREAD

**Issue by Sorceresssis** [Starry-OvO/Tieba-Cloud-Review#202]
**简要描述这个bug**

一些古老的帖子的语音的voice_md5是没有像 `_123456` 这样的后缀的。在爬取这些语音时FragVoice获取到的md5值会是31位，而不是32位。

虽然一些有`_123456` 这样后缀的语音可以正常获得32位的md5值。但是我不认为应该截去 `_123456` 后缀。因为voice_md5是语音文件的唯一标识。截去了后缀那么他也就失去了意义。无法通过它来下载语音文件了。

...

**如何复现**

在何种场景下用何种操作复现

tid=3446316934

错误的md5
pid=61142845967 floor=49  md5=9c891542e8d14f21d047f455b86ae22  url=https://tiebac.baidu.com/c/p/voice?voice_md5=9c891542e8d14f21d047f455b86ae22&play_from=pb_voice_play

正确的md5
pid=61142845967 floor=49  md5=9c891542e8d14f21d047f455b86ae22b  url=https://tiebac.baidu.com/c/p/voice?voice_md5=9c891542e8d14f21d047f455b86ae22b&play_from=pb_voice_play

**你希望程序作出何种行为**
应该直接返回voice_md5，不做任何截取处理。
![image](https://github.com/Starry-OvO/aiotieba/assets/63642310/ddd34b90-aced-4c04-8664-cd0773bf89ca)
...

**截图（可选）**

...

**Comment by n0099** [comment]
而我对[`PbContent.proto`](https://github.com/n0099/tbclient.protobuf/blob/7ebe461d60a24e336b930697f98cd6e3321a2aca/proto/PbContent.proto#L35)的唯一修改是针对统计上第二常见的`type=3图片`中的字段进行正义削除只留下`文件名hash`部分
https://github.com/n0099/open-tbm/commit/8477e817702e88ba5b853f7b92d0a79657dca9a3#diff-95921e765722e1b2e2c0ca1a1fe56c7431f408bb154416090f6cf27702806703R55
因为此前我还没大脑升级[`zfs+zstd透明压缩`](https://github.com/openzfs/zfs/pull/10278)立省[`2x压缩比`](https://dba.stackexchange.com/questions/315063/disable-toast-compression-for-all-columns/339329#339329)所以需要这样来节省（所有`PbContent.proto`encoding二进制中的）10%左右存储但现在有了压缩也没必要这样提前优化还打破了不修改贴吧返回的protobuf encoding二进制之承诺（假设[`protoc`](https://github.com/protocolbuffers/protobuf/releases)所codegen出的[parser/encoder](https://github.com/n0099/tbclient.protobuf/blob/7ebe461d60a24e336b930697f98cd6e3321a2aca/tbm_cs/Post/Common/Content.g.cs)可以保证`往复一致性`(`encode(parse(encoding))==encoding`)，然而目前只知道proto3保证了proto2时的行为：通过parse时放进[`unknownFields`](https://github.com/protocolbuffers/protobuf/issues/3395)来保留`.proto`中没定义的fieldnum）

**Comment by lumina37** [comment]
946b8f36f98fbc9ecd25fa1883240cd51155b9f3 应该修复了，看看能不能用

**Comment by Sorceresssis** [comment]
谢谢，可以正常使用了。
