### ISSUE TITLE
文档实用签到脚本易用性改进

### ISSUE THREAD

**Issue by lywlywly** [Starry-OvO/Tieba-Cloud-Review#209]
您好，首先非常感谢您写了这个百度贴吧API库。我使用您提供的[实用脚本](https://aiotieba.cc/tutorial/many_utils/)进行签到和一些日常任务，非常方便，

但我想针对文档中的每日签到脚本提几个建议，我提出这些建议主要原因是使用每日任务和签到脚本是我可以想象的这个库的受众最大的需求，大多数人期望安装好依赖后该脚本简单易用，然而目前文档存在一些没及时更新的地方。

1. 部分方法必须带`STOKEN`，但这一点没有在实用脚本里更新，也没有在任何地方解释这个`STOKEN`是个啥。如果没有`STOKEN`，log信息也不够self-explanatory。我后来摸索发现跟`BDUSS`一样是网页版百度贴吧的cookie，但这无疑造成了一定的障碍。
1. 签到脚本的以下片段
   https://github.com/Starry-OvO/aiotieba/blob/2be7657d58a40ba0be69cdd26755d8848b54face/docs/tutorial/many_utils.md?plain=1#L37-L48
   这里进行了一个对您本人账号进行关注的操作，然而一般人看到这串魔法数字可能没法理解。我因为尝试过爬取贴吧网页版，知道这是[个人主页portrait的格式](https://tieba.baidu.com/home/main?id=tb.1.2fc1394a.ukuFqA26BTuAeXqYr1Nmwg)。这也是该教学文档不明确的地方。不过对于关注你这件事我觉得挺幽默的（字面意思，很有意思的小彩蛋），作为代码里的一个小彩蛋也没什么。

总之，非常感谢您开发了这个库，我理解作者因为业余时间的原因这个库本并不打算也没有必要做到well-documented，但我觉得签到脚本作为一个新手向的脚本需要进行一些改进能让它确实是易用的。

**Comment by n0099** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign
https://github.com/BANKA2017/tbsign_go

**Comment by lumina37** [comment]
> https://github.com/MoeNetwork/Tieba-Cloud-Sign https://github.com/BANKA2017/tbsign_go

我这个库其实没什么人会拿来签到，所以那个文档基本没怎么更新过，或者默认了读者是签到工具的开发者。非贴吧开发者的用户还是建议用上面带GUI的签到。

另外那些互关代码是成长值任务的一部分。

**Comment by adk23333** [comment]
自动签到工具太多了，印象中确实没啥人用这个写签到哈哈
