### ISSUE TITLE
tid: 4025914848 楼中楼内容中用于表示回复者的 FragAt 数据错误。

### ISSUE THREAD

**Issue by Sorceresssis** [Starry-OvO/Tieba-Cloud-Review#214]
**简要描述这个bug**

tid: 4025914848 第二楼的楼中楼内容中用于表示回复者的 FragAt 数据错误。

**如何复现**

在何种场景下用何种操作复现

楼中楼位置。
tid: `4025914848`
floor: `2`, pid:`75363365497`
楼中楼第 `2` 楼, pid:`75497714390`

![image](https://github.com/user-attachments/assets/adf83d22-459d-4fbe-8e85-570133d5317b)

FragAt 的数据错误，`text` 字段乱码，`user_id`字段为0
正确的值应为  `卡艾王`, `1097650720`

```json
"objs": [
    {
        "text": "回复 "
    },
    {
        "text": "������",
        "user_id": 0
    },
    {
        "text": ":谁啊"
    },
    {
        "id": "image_emoticon21",
        "desc": "呼~"
    }
],
```

**Comment by lumina37** [comment]
这个客户端里就是乱码，搞不定

**Comment by n0099** [comment]
> 楼中楼第 `2` 楼, pid:`75497714390`

那叫spid，`楼中楼` `回复贴`本质完完全全同路人而贴吧命名法称其`(sub)post` https://github.com/Starry-OvO/aiotieba/issues/114#issuecomment-1515776671

```bash
$ curl -s https://n0099.net/tbm/v1/client_tester.php\?type\=lzls\&tid\=4025914848\&pid\=75363365497\&pn\=1\&client_version\=8.8.8.8 \
| jq '.subpost_list[] | select(.id == 75497714390) | .content'
[
  {
    "text": "回复 ",
    "type": 0
  },
  {
    "type": 4,
    "text": "������",
    "uid": 0
  },
  {
    "type": 0,
    "text": " :谁啊"
  },
  {
    "type": 2,
    "text": "image_emoticon21",
    "c": "呼~"
  }
]
```
经典`unicode replacement char` https://codepoints.net/U+FFFD https://en.wikipedia.org/wiki/Specials_(Unicode_block) 盲猜是gbk/2312转utf8时卡bug
```bash
$ echo -n 卡艾王 | tee >(hexdump) | wc -c
9
0000000 8de5 e8a1 be89 8ee7 008b
0000009
$ echo -n 卡艾王 | iconv -t GB2312 | tee >(hexdump) | wc -c
0000000 a8bf acb0 f5cd
0000006
6
```
`卡艾王`在gb2312下是6字节恰好与这6个`replacement char`数量相同

**Comment by Sorceresssis** [comment]
乱码无所谓的，难受的是 user_id 获取不到，知道 user_id 就可以直接去替换nickname。
贴吧网页版意外的兼容性很好。我想可以结合传统的网页爬虫来完善数据。但是要实现 `贴吧官方网页` 和 `aiotieba` 的爬取同步非常麻烦。网页没有固定的 `rn` ，每页帖子的数量都不固定。得依靠二分法一点一点的遍历查找。

**Comment by n0099** [comment]
> 乱码无所谓的

请不要将任何人类不可读的一坨神必字符（如base64encoding https://z.n0099.net/#narrow/near/92764 uuid https://github.com/n0099/open-tbm/issues/24 ）称做乱码除非的确不知道其是什么
您已经知道这是6个`U+FFFD Replacement Character`了

> `贴吧官方网页` 和 `aiotieba` 的爬取同步

是`网页端`接口和`客户端`接口
还存在着`wap网页`接口（ https://tieba.baidu.com/mo 疑似已在 https://github.com/Starry-OvO/aiotieba/issues/124#issuecomment-1556355555 https://github.com/Starry-OvO/aiotieba/issues/199#issuecomment-2133252453 之后强制赶人到后者）和`移动端网页`（使用移动端设备UA访问`网页端`的url aka所谓的 https://en.wikipedia.org/wiki/Content_negotiation ）接口

> 网页没有固定的 `rn` ，每页帖子的数量都不固定。

https://tieba.baidu.com/p/4025914848 登录态下`主题帖回复帖`是`rn=30` https://github.com/Starry-OvO/aiotieba/issues/158#issuecomment-1913593298 没登录是`15`
https://tieba.baidu.com/p/comment?tid=4025914848&pid=75363365497&pn=1 `回复贴楼中楼`固定是`10`

> 得依靠二分法一点一点的遍历查找。

只要`客户端`接口和`网页端`接口使用相同的`rn`那使用相同的`pn`查询就能对齐上
不考虑有些`主题帖` `回复贴`如两套`投票帖` https://github.com/Starry-OvO/aiotieba/issues/83#issuecomment-1384091976 https://github.com/Starry-OvO/aiotieba/issues/124#issue-1718690730 是`网页端`/`客户端`特供仅在该接口下可见
