### ISSUE TITLE
重写部分类的str方法

### ISSUE THREAD

**Issue by QuickBrownFox666** [Starry-OvO/Tieba-Cloud-Review#217]
**我需要什么功能**
重写有关类的str方法，使得其转化为字符串时更为直观。例如重写存放回贴的类的str方法。

**我想将这个功能应用于何种场景**
例如：在直接print内容碎片时，直接将其以较为直观的方式展示，而不是用python默认的class嵌套class的方式来展示。
或者为相关类增加一个有类似功能的方法。

**Comment by n0099** [comment]
> 在直接print内容碎片时，直接将其以较为直观的方式展示

什么 https://n0099.net/tbm/__og-image__/image/posts/fid/97650/og.png https://github.com/n0099/open-tbm/blob/c0f594be5190274ae4978254500389d091c34f2c/fe/src/utils/post/renderer.ts#L143-L144

**Comment by lumina37** [comment]
这个str是为删帖机日志设计的，需要单行打印并保留所有信息，我觉得有点难改

**Comment by QuickBrownFox666** [comment]
> 这个str是为删帖机日志设计的，需要单行打印并保留所有信息，我觉得有点难改

那是否可以对于某些必要的类添加对应的方法？例如.format()之类的

**Comment by n0099** [comment]
> 需要单行打印并保留所有信息

[`protoc`](https://github.com/protocolbuffers/protobuf/releases)codegen的api里有个`tojson()` https://github.com/n0099/open-tbm/blob/c0f594be5190274ae4978254500389d091c34f2c/c%23/crawler/src/Db/ProtoBufRepeatedFieldJsonConverter.cs#L12 https://github.com/n0099/open-tbm/blob/c0f594be5190274ae4978254500389d091c34f2c/be/app/Eloquent/ModelAttributeMaker.php#L29

**Comment by lumina37** [comment]
而且我也不太知道这功能的应用场景
