### ISSUE TITLE
如果频繁获取数据会被封号吗

### ISSUE THREAD

**Issue by codinghahaha** [Starry-OvO/Tieba-Cloud-Review#225]

**Comment by lumina37** [comment]
不会，我们的云审查基本顶着rps上限在跑

**Comment by n0099** [comment]
rps https://github.com/Starry-OvO/aiotieba/issues/82#issuecomment-1381728181

**Comment by codinghahaha** [comment]
厉害了，大佬

**Comment by n0099** [comment]
另外大多数`httpmethod之GET`只读语义（反例如`封人` `删帖`是`非GET`的写语义）的接口不需要带上bduss https://github.com/Starry-OvO/aiotieba-reviewer/issues/18#issuecomment-1556213569

**Comment by codinghahaha** [comment]
@n0099 不带bduss，GET会有限制吗？会不会有些信息获取不到？

**Comment by n0099** [comment]
什么接口？您一直都没说您到底在调`什么接口`获取`什么数据`想要`什么信息`
对于我用的那3个接口`吧首页主题帖` `主题帖回复贴` `回复贴楼中楼`带上bduss我只知道会增加`个性化广告/feed`和自己发的正在`主客态` https://en.wikipedia.org/wiki/Shadow_banning 中的帖子以及可能的 https://github.com/Starry-OvO/aiotieba-reviewer/issues/18#issuecomment-1556213569

**Comment by codinghahaha** [comment]
@n0099 我想用的就是您说的三个接口。明白了，感谢
