### ISSUE TITLE
主题帖获取问题

### ISSUE THREAD

**Issue by codinghahaha** [Starry-OvO/Tieba-Cloud-Review#226]
![FastStoneEditor1](https://github.com/user-attachments/assets/c58e3d52-d9dc-41df-adc2-6e3d85d8408d)
![2024-08-29_215319](https://github.com/user-attachments/assets/c10a5d3f-2af7-4ae1-a8a6-6ca736d70cc1)
page_size=105，最大能获取100条。剩余5条该怎么获取呢？

**Comment by n0099** [comment]
`current_page=3`
https://github.com/n0099/tbclient.protobuf/blob/12.51.7.1/proto/Page.proto#L9
```py
while page.has_more = 1
    current_page++
```

**Comment by codinghahaha** [comment]
@n0099 我测试了，翻到下一页是从下一页开始获取，上一页的最后5条获取不到的。

**Comment by n0099** [comment]
`rn`是您要求贴吧每`pn`给您多少帖子
然而其服务端显然有着给您返回`任意多条帖子`的自由例如插入一些LLM https://github.com/Starry-OvO/aiotieba/issues/210#issuecomment-2225305837 广告 https://github.com/Starry-OvO/aiotieba/issues/216#issuecomment-2278878131
您应该以其实际返回了多少帖子而非您提供的`rn`为准
最简单的例子：如果您请求的`pn`根本不存在（亦或该`pn`没有那么多帖子）那显然应该期望其返回`0`（亦或该`pn`下的所有帖子）条而非您要求的`rn`条帖子
另外对于[offset pagination](https://use-the-index-luke.com/no-offset)之`pn`更好的是[cursor/keyset pagination](https://hn.algolia.com/?query=cursor+pagination) 正如同年初的 https://github.com/Starry-OvO/aiotieba/issues/158#issuecomment-1913593298

**Comment by lumina37** [comment]
有测试样本吗，比如哪个帖的后五条回复获取不到

**Comment by codinghahaha** [comment]
![FastStoneEditor122](https://github.com/user-attachments/assets/1cdb3955-1b4f-4bb5-9a6f-41783ba6fabf)
![FastStoneEditor1](https://github.com/user-attachments/assets/9f1a8386-2753-4e0c-951d-7bd8040c8be2)
@Starry-OvO 我调用的是get_threads接口，获取帖子时后最后五条获取不到，不是帖子的回复。我是在土木工程吧测试的。上面两张图感觉像是一瓶105ml的水，最多只能喝100ml

**Comment by n0099** [comment]
> 上面两张图感觉像是一瓶105ml的水，最多只能喝100ml

是贴吧只给您至多`100ml`的水，想要喝`105ml`就必须换`下一瓶`然后倒掉剩余的`95ml`

https://github.com/Starry-OvO/aiotieba/issues/226#issuecomment-2317948812
> ```python
> while page.has_more = 1
>     current_page++
> ```

**Comment by codinghahaha** [comment]
@n0099 一瓶水喝不完，最后5ml只能倒掉嘛。把req_proto.data.rn = 105，改成req_proto.data.rn = 100，一瓶水改成100ml的，最多喝100ml。这样改行不行，还是说会引出其他问题。

**Comment by n0099** [comment]
> 是贴吧只给您至多`100ml`的水

而非您能喝多少水的问题
所以为什么要用奇怪的现实类比徒增抽象隔离？

**Comment by codinghahaha** [comment]
改成req_proto.data.rn = 100可以的

**Comment by lumina37** [comment]
虽然不知道之前为什么要设rn=105不过应该是有道理的

——《屎山的诞生》

**Comment by n0099** [comment]
https://github.com/Starry-OvO/aiotieba/commit/6a70a5bd92c2f2f419d30af7205a2fe31285dafe#diff-1b7e1df8383da27d0517a40fabe0e965c2d7a435983688a5d6ee0ce6f023dd4bR16
因为这只有`rn_need`才是真的`rn`
而由于 https://github.com/Starry-OvO/aiotieba/issues/83#issuecomment-1385431543 必须让 $$rn>rn\\_need$$ 所以随便来个比`rn`上限`100`大的数，我自换到protobuf接口 https://github.com/n0099/open-tbm/commit/a83b672b6bc9cc56b2d1382529f2bb9575837cb2#diff-c631ae64eec29d54d4c85f3831440863196a63d90205f7f36c78129588152c6dR55 以来一直是`rn=90` `rn_need=30`但我也忘了`22年`时为什么要这样设`大3倍`从而避免了 https://github.com/Starry-OvO/aiotieba/issues/83#issuecomment-1384277923

**Comment by codinghahaha** [comment]
rn>rn_need会漏爬数据

**Comment by n0099** [comment]
> 因为这只有`rn_need`才是真的`rn`

您设`rn_need=100` `rn=114514`贴吧也只会给您`100条`主题帖
但如果 $$rn<=rn\\_need$$ 对某些`(fid, pn)`组合就可能`100条`都没有（假设该`pn`下有那么多主题帖）
