### ISSUE TITLE
远古`IP匿名`楼主主题帖在`吧首页主题帖列表`接口中不可见

### ISSUE THREAD

**Issue by n0099** [Starry-OvO/Tieba-Cloud-Review#228]
https://web.archive.org/web/20240902210034/https://tieba.baidu.com/f?kw=%E6%A8%A1%E6%8B%9F%E5%9F%8E%E5%B8%82&ie=utf-8&pn=46450
https://web.archive.org/web/20240902205916/https://n0099.net/tbm/v1/client_tester.php?type=posts&forum=%E6%A8%A1%E6%8B%9F%E5%9F%8E%E5%B8%82&pn=929&rn=50&client_version=6.0.2
```bash
curl -s 'https://n0099.net/tbm/v1/client_tester.php?type=posts&forum=模拟城市&pn=929&rn=50&client_version=6.0.2' \
| jq '.thread_list[] | .author.id'
```
```
1278607
5281245
4306102
2542318
3327856
216561
3953048
3842146
```
https://web.archive.org/web/20240902205924/https://n0099.net/tbm/v1/client_tester.php?type=posts&forum=%E6%A8%A1%E6%8B%9F%E5%9F%8E%E5%B8%82&pn=929&rn=50&client_version=12.64.1.1
```bash
curl -s 'https://n0099.net/tbm/v1/client_tester.php?type=posts&forum=模拟城市&pn=929&rn=50&client_version=12.64.1.1' \
| jq '.thread_list[] | .author_id'
```
```
1278607
5281245
4306102
2542318
3327856
216561
3953048
3842146
```
前些年还是可见的而目前客户端接口比网页端少了所有`IP匿名`楼主的主题帖所以所有主题帖都有`非0百度uid`

例如目前第一页上的 https://tieba.baidu.com/p/434920124
对这些tid使用`主题帖回复帖列表`或`回复贴楼中楼列表`接口也还是能看到`百度uid0` https://github.com/Starry-OvO/aiotieba/issues/213 的`IP匿名`楼主
```bash
curl -s 'https://n0099.net/tbm/v1/client_tester.php?type=replies&tid=434920124&pn=1&client_version=12.64.1.1' | jq '.post_list[] | .author_id'
```
```
0
68848908
812592769
243784075
```

**Comment by lumina37** [comment]
然而我们好像也修不了

**Comment by n0099** [comment]
我知道，因为这是服务端暗改
目前只能再爬一遍网页端吧首页得出其与客户端接口的tid差集
