### ISSUE TITLE
add_bawu_blacklist函数不能使用

### ISSUE THREAD

**Issue by QuickBrownFox666** [Starry-OvO/Tieba-Cloud-Review#231]
**简要描述这个bug**

add_bawu_blacklist函数不能使用

**如何复现**

使用函数后报WARNING，我确定我传的是用户名而不是昵称。

[WARN] [add_bawu_blacklist] (2210002, 'user not right'). args=('吧名', '用户名') kwargs={}

**你希望程序作出何种行为**

正常工作

**Comment by QuickBrownFox666** [comment]
补充：BDUSS和STOKEN全部传了

**Comment by lumina37** [comment]
你使用的账号是那个吧的大吧主吗

**Comment by QuickBrownFox666** [comment]
> 你使用的账号是那个吧的大吧主吗

是的 @lumina37

**Comment by lumina37** [comment]
我刚试了一下，可能是因为那个用户没关注你们吧，所以拉不了黑名单

**Comment by QuickBrownFox666** [comment]
@lumina37 嗯，是没关注

**Comment by lumina37** [comment]
那就不是库的问题了，是贴吧的后台设置问题

**Comment by n0099** [comment]
> @lumina37 嗯，是没关注

不关注本来就无法拉黑因为吧主拉黑实际上就是使其取消关注贵吧（经验等级显示为1级且不能签到，但发言等其他权限仍然正常）

**Comment by QuickBrownFox666** [comment]
> 那就不是库的问题了，是贴吧的后台设置问题

此外这个项目好像把很多的Succeeded写作Suceeded，算是个typo，感觉能处理一下最好。

**Comment by n0099** [comment]
https://github.com/lumina37/aiotieba/blob/43aa5f7b64bc2ed8badeb7c5a6d15909308b6bec/aiotieba/helper/utils.py#L78
https://github.com/lumina37/aiotieba/issues/119#issuecomment-1538389886
https://github.com/lumina37/aiotieba/issues/97#issue-1573599333

**Comment by lumina37** [comment]
> > 那就不是库的问题了，是贴吧的后台设置问题
> 
> 此外这个项目好像把很多的Succeeded写作Suceeded，算是个typo，感觉能处理一下最好。

已经处理了，感谢提醒 8c40349d4963fe0aae616e9c6716ff198bee82ad
