### ISSUE TITLE
填入BDUSS 按照入门教程运行debug.py无法登陆

### ISSUE THREAD

**Issue by wubushanyan** [Starry-OvO/Tieba-Cloud-Review#24]
**简要描述这个bug**
填入BDUSS 按照入门教程运行debug.py报错
提示：
<2022-07-01 15:42:47> [WARNING] Failed to login. reason:请点击“取消”按钮，打开首页后手动输入帐号信息完成登录。
<2022-07-01 15:42:47> [INFO] 当前用户信息: BasicUserInfo [user_id:0 / user_name: / portrait: / nick_name:]

**如何复现**
粘贴BDUSS ，复制入门教程debug.py代码，运行、、

**环境**
centos7.8（国外）
python 3.9
pip 22.0.4

**截图（可选）**
![image](https://user-images.githubusercontent.com/56383722/176927830-7b8121de-b82c-4baa-82be-347ebfd0d1a9.png)

**Comment by lumina37** [comment]
检查一下填写的BDUSS是不是192个字符，以及BDUSS是不是来自已登录的账号
手动注销来源账号的登录态，或者在设备管理中退出对应设备都可能会导致BDUSS失效并报这个错误

**Comment by wubushanyan** [comment]
> 检查一下填写的BDUSS是不是192个字符，以及BDUSS是不是来自已登录的账号 手动注销来源账号的登录态，或者在设备管理中退出对应设备都可能会导致BDUSS失效并报这个错误

应该是失效了，注销后成功了 感谢帮助
