### ISSUE TITLE
还还还是主题帖获取问题

### ISSUE THREAD

**Issue by Misaka19327** [Starry-OvO/Tieba-Cloud-Review#244]
``` python
async def main():
    async with (tb.Client(BDUSS) as client):
        info = await client.get_posts(tid=9180480284)
        print(info.thread.title)
        print(info.thread.agree)

asyncio.run(main())
```

代码如上，报错`[WARN] [get_posts] Client.get_posts() got some positional-only arguments passed as keyword arguments: 'tid'. args=() kwargs={'tid': 9205167552}`，这个帖子确实存在，是我方法用错了么

**Comment by lumina37** [comment]
position-only参数不能以key-value（也就是tid=1234567）的形式传入

**Comment by Misaka19327** [comment]
多谢 已解决

**Comment by n0099** [comment]
https://github.com/lumina37/aiotieba/commit/e65137618877f6ddf6fa7da416dca0e4405fd93e
