### ISSUE TITLE
您操作的太频繁了

### ISSUE THREAD

**Issue by ODtian** [Starry-OvO/Tieba-Cloud-Review#39]
**简要描述这个bug**

点赞时出现您操作的太频繁了

**如何复现**

用示例里的签到水贴点赞脚本

**你希望程序作出何种行为**

我用asyncio的信号量控制并发数为2，但是点赞的吧一多就开始提示，等了几个小时还是提示，手机版可以正常点赞，这个是已知的限制吗，有的话可以找个地方提示一下

**截图（可选）**

无

**Comment by lumina37** [comment]
那个例子需要优化。
因为当时我调试那个点赞接口的时候发现可以无限点，用大号在v吧点了几百经验出来之后就说不了话了（发回复秒删），后面还是用了休克疗法（刷回复刷到永封再解封）才能发帖。后面他们程序员可能是发现了异常，就加强了限制，现在点个十几次就会操作频繁了。
这个点赞接口的风险仅次于发帖接口。狂暴轰入发帖接口会导致永封，狂暴轰入点赞接口会导致发帖秒删，所以一般每个吧点三下就差不多了

**Comment by lumina37** [comment]
刚刚更新了例子，还有两个高风险接口的注释

> 2e745e60deffac421d2ad3d7bdc8ad102b46c757

**Comment by lumina37** [comment]
也可能是我参数没还原好。毕竟这个新版点赞接口是极少数强制要求cuid参数的接口

**Comment by ODtian** [comment]
好嘞👌

**Comment by n0099** [comment]
> 刷回复刷到永封再解封

您走点贴吧大神解封通道？

**Comment by Starry-OvO** [comment]
官方申诉足够快了

n0099 ***@***.***> 于 2022年8月11日周四 21:42写道：

**Comment by lumina37** [comment]
> > 刷回复刷到永封再解封
> 
> 您走点贴吧大神解封通道？

官方申诉足够快了
