### ISSUE TITLE
云审查使用求助

### ISSUE THREAD

**Issue by RootSir** [Starry-OvO/Tieba-Cloud-Review#60]
[WARN] [compute_imghash] module 'cv2' has no attribute 'img_hash'

这个怎么解决，谢谢大佬

**Comment by RootSir** [comment]
I uninstalled both opencv-python and opencv-contrib-python and then installed only opencv-contrib-python.
解决了。

**Comment by lumina37** [comment]
这个是[opencv附加库](https://docs.opencv.org/4.6.0/d4/d93/group__img__hash.html) 里的函数，而且4.6.0和4.5.5的api还是不一样的
