### ISSUE TITLE
程序不会自动创建数据库和表？

### ISSUE THREAD

**Issue by Hawaii-ol** [Starry-OvO/Tieba-Cloud-Review#61]
使用my_reviewer.py时一直报数据库连接错误，折腾半天后发现是没有创建数据库（因为我以为会自动创建）
手动执行CREATE DATABASE aiotieba后，重新运行程序又报错(1146, "Table 'aiotieba.user_id_XXX' doesn't exist")
所以程序不会创建数据库和表吗？我注意到database.py中有create_database方法，但这个方法从未被使用，也没有在示例中说明
框架是否应该在Reviewer初始化时（或者__aenter__中）先调用db.create_database方法？

**Comment by lumina37** [comment]
目前的解决方案，参考[云审查教程](https://v-8.top/tutorial/reviewer/) 
使用如下脚本创建并初始化数据库
```
import asyncio

import aiotieba as tb


async def main() -> None:
    async with tb.MySQLDB("在这里填你要审查的贴吧名") as brow:
        await brow.create_database()


asyncio.run(main())
```
这确实是一个有待改进的问题。因为我当时对mysql的错误码了解得还不够，等考试结束后我会再针对具体错误码改进自动建表的逻辑
