### ISSUE TITLE
无法获取post[n]的user对象

### ISSUE THREAD

**Issue by z6189949** [Starry-OvO/Tieba-Cloud-Review#67]
**简要描述这个bug**
去年功能一切正常，从2023年开始无法获取到post里的每个用户的个人信息
...

**如何复现**
使用client.get_posts方法
在何种场景下用何种操作复现

**你希望程序作出何种行为**
统计每个发帖人 回帖人的用户名 昵称 归属地
...

**截图（可选）**
![image](https://user-images.githubusercontent.com/38304059/210474342-831896f4-d055-4863-8b2b-bd993b46d88b.png)
![image](https://user-images.githubusercontent.com/38304059/210474455-5f062053-a2f3-4a3a-8535-d23642fb4b83.png)

...

**Comment by n0099** [comment]
https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368179653

**Comment by z6189949** [comment]
> [#64 (comment)](https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368179653)

现在我只能暂时使用get_user_info接口，有没有更方便的方法呢

**Comment by n0099** [comment]
cc @Starry-OvO

**Comment by lumina37** [comment]
升级到2.10.1试试
0bd449d0cf2d3a8b7a7aa9799d05b378deb6cdce 应该能解决问题

**Comment by n0099** [comment]
> [#64 (comment)](https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368179653)
> 并且还是灰度发布（随机返回修改后或之前的结构）的，导致我不得不同时保留对两种结构的处理并回退： https://github.com/n0099/TiebaMonitor/commit/0e7d15bcb188da781055a573c899acfb97eacd50

贴吧后端好像做完灰度全量发布使用滚回7.x及以前版本客户端json接口中的冗余结构：把每个回复贴的用户元数据都放在`reply.author`下，这下主题帖回复贴楼中楼3大接口都一致了（以前只有楼中楼接口还是7.x及以前的结构）

我在 https://github.com/n0099/TiebaMonitor/blob/1ed0332563d4deb02201cb2a3b18ce8816a68d9d/crawler/src/Tieba/Crawl/Facade/ReplyCrawlFacade.cs#L23 加的如下两个断点显示只有第二个断点（`reply.author`）会触发而第一个（`user_list`）不会
![image](https://user-images.githubusercontent.com/13030387/210869252-2047b107-f043-4bf4-89bd-85c6f46c8d87.png)

**Comment by n0099** [comment]
https://github.com/Starry-OvO/aiotieba/releases/tag/v2.10.2 中进一步指出：
> https://github.com/Starry-OvO/aiotieba/issues/67 https://github.com/Starry-OvO/aiotieba/issues/68 描述的bug的产生原因是 /pb/page 接口新增了对 _client_type 参数的依赖，缺失该参数会导致获取的数据归属于默认的远古版本，表现出的具体特征有: 返回用户昵称为旧版， user_list 不包含数据，无法识别音频内容等。因此在添加上 _client_type 参数后， 2.10.1 的以下变化可以被安全地回滚: FragImage.big_src 被重新添加， FragLink.is_external 恢复由 /mo/q/checkurl 前缀判断， Posts 和 Threads 的解析流程仅保留【同时使用 user_list + author_id 字段】而弃用【直接使用 author 字段】

所以带个`_client_type=2`就可以变回user_list结构了？

**Comment by lumina37** [comment]
Of course
