### ISSUE TITLE
封禁用户功能失效

### ISSUE THREAD

**Issue by Hawaii-ol** [Starry-OvO/Tieba-Cloud-Review#68]
从昨天起日志发现无法获取到用户信息，且block时提示以下信息

<2023-01-04 03:42:06.073> [INFO] [_exce_delete] Del Post. text=昆鹏发卡网，卡密，秘钥自动发货，虚拟产品自动发货 user=0 level=0 note=L81 推广网站/产品/群聊等广告行为
<2023-01-04 03:42:07.709> [INFO] [del_post] Succeeded. forum=abc pid=123 （具体的forum和pid就不写了）
<2023-01-04 03:42:07.710> [WARN] [get_user_info] Null input
<2023-01-04 03:42:07.916> [WARN] [block] (300000, '由于系统升级，烦请您更新至最新版客户端处理违规用户，感谢您的理解与支持！'). forum=abc user=0 day=1

看起来似乎是贴吧客户端接口升级了。有什么跟进吗？

**Comment by n0099** [comment]
> 昨天起日志发现无法获取到用户信息

https://github.com/Starry-OvO/aiotieba/issues/67

**Comment by lumina37** [comment]
升级到2.10.1试试
0bd449d0cf2d3a8b7a7aa9799d05b378deb6cdce 应该能解决问题

**Comment by Hawaii-ol** [comment]
> 升级到2.10.1试试 [0bd449d](https://github.com/Starry-OvO/aiotieba/commit/0bd449d0cf2d3a8b7a7aa9799d05b378deb6cdce) 应该能解决问题

感谢！现在已经可以了
