### ISSUE TITLE
关于返回帖子时间

### ISSUE THREAD

**Issue by liuxiaolei88** [Starry-OvO/Tieba-Cloud-Review#94]
**我需要什么功能**
您好，想问一下调用get_posts()以后如何可以返回更多的帖子内容呢，例如时间，来自xxx客户端等。谢谢
...

**我想将这个功能应用于何种场景**

...

**Comment by n0099** [comment]
1. 哪个时间？
2. json版本`c/f/pb/page`接口里已经删除了的`thread.thread_info.phone_type`： https://github.com/Starry-OvO/aiotieba/issues/64#issuecomment-1368179653 https://github.com/n0099/TiebaMonitor/blob/8b6f7a179f030726c9810a372403846ba5562ebf/crawler/src/Tieba/Crawl/ThreadLateCrawlerAndSaver.cs#L77

**Comment by liuxiaolei88** [comment]
十分感谢您的回复！
    时间指的是发楼的时间。我在get_post函数里看到create_post字段，可以通过修改这部分代码获取时间吗？
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年1月27日 16:56
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            XiaoLei ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Starry-OvO/aiotieba] 关于返回帖子时间 (Issue #94)
        
      
    
  
  



哪个时间？

json版本c/f/pb/page接口里已经删除了的thread.thread_info.phone_type： #64 (comment) https://github.com/n0099/TiebaMonitor/blob/8b6f7a179f030726c9810a372403846ba5562ebf/crawler/src/Tieba/Crawl/ThreadLateCrawlerAndSaver.cs#L77

**Comment by lumina37** [comment]
创建时间就是`post.create_time`

**Comment by liuxiaolei88** [comment]
感谢回复！
